import type { CardUseScoreContext } from './card-scoring/context';
import {
    applyIsRecoveryCardScore,
    applyIsHoldCardScore,
    applyHasCornerMoveNowScore,
    applyHasCornerMoveNowScore3,
    applyWhiteLv6ModeScore,
    applyHasCornerMoveNowScore5,
    applyIsChargeRampCardScore,
    applyIsChargeSwingCardScore,
    applyIsGoldStoneScore,
    applyIsCrystalStoneScore,
    applyIsTreasureBoxScore,
    applyIsFreePlacementScore
} from './card-scoring/economy';
import {
    applyIsSniperWillScore,
    applyIsStrongWindWillScore,
    applyIsSwapWithEnemyScore,
    applyIsTemptWillScore,
    applyIsCloneWillScore,
    applyIsThrowChainCardScore,
    applyIsChainWillScore,
    applyIsBoardExpansionWillScore,
    applyIsBoardShrinkCardScore,
    applyIsTrapWillScore,
    applyIsHeavenBlessingScore,
    applyIsRevealHandWillScore,
    applyIsCondemnWillScore,
    applyIsExecutionWillScore,
    applyIsExtendLifeCardScore,
    applyIsProtectedNextStoneScore,
    applyIsLightningWillScore
} from './card-scoring/control';
import {
    applyIsHyperactiveWillScore,
    applyIsTabooReverseWillScore,
    applyIsCrossBombScore,
    applyIsUltimateDestroyGodScore,
    applyIsUltimateHyperactiveGodScore,
    applyIsDestroyDragonWillScore,
    applyIsBreedingWillScore,
    applyIsTeleportWillScore,
    applyIsCellTeleportWillScore,
    applyIsHyperactiveInheritWillScore,
    applyIsRobotVacuumWillScore,
    applyIsEqualityWillScore,
    applyIsReinforcementWillScore,
    applyIsGluttonousWillScore,
    applyIsExtremeHyperactiveWillScore
} from './card-scoring/stones';
import {
    applyIsSuperCrushWillScore,
    applyIsBlockadeWillScore,
    applyIsMeteorWillScore,
    applyLeadStableScore,
    applyIsLossWillScore,
    applyIsMassFreezeWillScore,
    applyIsCorrosionWillScore,
    applyIsRebuildWillScore,
    applyIsWorkWillScore,
    applyIsTimeBombScore,
    applyIsTimeStopGodScore,
    applyWhiteLv6ModeScore55
} from './card-scoring/late-game';

// Order preserves the historical sequential arithmetic, including overlapping rules.
const CARD_USE_SCORE_RULES = Object.freeze([
    applyIsRecoveryCardScore,
    applyIsHoldCardScore,
    applyHasCornerMoveNowScore,
    applyHasCornerMoveNowScore3,
    applyWhiteLv6ModeScore,
    applyHasCornerMoveNowScore5,
    applyIsChargeRampCardScore,
    applyIsChargeSwingCardScore,
    applyIsGoldStoneScore,
    applyIsCrystalStoneScore,
    applyIsTreasureBoxScore,
    applyIsFreePlacementScore,
    applyIsSniperWillScore,
    applyIsStrongWindWillScore,
    applyIsSwapWithEnemyScore,
    applyIsTemptWillScore,
    applyIsCloneWillScore,
    applyIsThrowChainCardScore,
    applyIsChainWillScore,
    applyIsBoardExpansionWillScore,
    applyIsBoardShrinkCardScore,
    applyIsTrapWillScore,
    applyIsHeavenBlessingScore,
    applyIsRevealHandWillScore,
    applyIsCondemnWillScore,
    applyIsExecutionWillScore,
    applyIsExtendLifeCardScore,
    applyIsProtectedNextStoneScore,
    applyIsLightningWillScore,
    applyIsHyperactiveWillScore,
    applyIsTabooReverseWillScore,
    applyIsCrossBombScore,
    applyIsUltimateDestroyGodScore,
    applyIsUltimateHyperactiveGodScore,
    applyIsDestroyDragonWillScore,
    applyIsBreedingWillScore,
    applyIsTeleportWillScore,
    applyIsCellTeleportWillScore,
    applyIsHyperactiveInheritWillScore,
    applyIsRobotVacuumWillScore,
    applyIsEqualityWillScore,
    applyIsReinforcementWillScore,
    applyIsGluttonousWillScore,
    applyIsExtremeHyperactiveWillScore,
    applyIsSuperCrushWillScore,
    applyIsBlockadeWillScore,
    applyIsMeteorWillScore,
    applyLeadStableScore,
    applyIsLossWillScore,
    applyIsMassFreezeWillScore,
    applyIsCorrosionWillScore,
    applyIsRebuildWillScore,
    applyIsWorkWillScore,
    applyIsTimeBombScore,
    applyIsTimeStopGodScore,
    applyWhiteLv6ModeScore55,
]);

export function applyCpuCardScoreRules(context: CardUseScoreContext, initialScore: number): number {
    let score = initialScore;
    for (const rule of CARD_USE_SCORE_RULES) score = rule(context, score);
    return score;
}
