function requireOptionalModule(id: string): any {
    try {
        return require(id);
    } catch (e) {
        return null;
    }
}

const SharedCardHeuristics = requireOptionalModule('../../shared/shared-card-heuristics');

const THROW_CHAIN_CARD_TYPES = Object.freeze(['DOUBLE_PLACE', 'TRIPLE_PLACE', 'QUAD_PLACE', 'INFINITE_PLACE']);
const CHAIN_WILL_CARD_TYPES = Object.freeze(['DOUBLE_CHAIN_WILL', 'TRIPLE_CHAIN_WILL', 'QUAD_CHAIN_WILL', 'INFINITE_CHAIN_WILL']);

const DEFENSIVE_CARD_TYPES = new Set([
    'PROTECTED_NEXT_STONE',
    'AFTERIMAGE_WILL',
    'GHOST_WILL',
    'PERMA_PROTECT_NEXT_STONE',
    'GUARD_WILL',
    'GUARDIAN_GOD',
    'REGEN_WILL',
    'HEAVEN_BLESSING',
    'REVEAL_HAND_WILL',
    'CONDEMN_WILL',
    'OBSERVER_WILL',
    'THEORY_INCARNATION',
    'EXECUTION_WILL',
    'TRAP_WILL',
    'EXTEND_LIFE_WILL',
    'EXTEND_LIFE_GOD',
    'SNIPER_WILL',
    'LIGHTNING_WILL',
    'METEOR_GOD',
    'SALVATION_WILL',
    'STONE_SALVATION_GOD',
    'REINFORCEMENT_WILL',
    'SUPPORT_TROOPS_WILL',
    'LIVING_WILL'
]);

const HIGH_VARIANCE_CARD_TYPES = new Set([
    'ULTIMATE_REVERSE_DRAGON',
    'ULTIMATE_DESTROY_GOD',
    'ULTIMATE_HYPERACTIVE_GOD',
    ...THROW_CHAIN_CARD_TYPES,
    ...CHAIN_WILL_CARD_TYPES,
    'TEMPT_WILL',
    'CAPTURE_WILL',
    'POSITION_SWAP_WILL',
    'SWAP_WITH_ENEMY',
    'TIME_BOMB',
    'TIME_STOP_GOD',

    'TIME_STOP_DEITY',
    'CROSS_BOMB',
    'X_BOMB',
    'BREEDING_WILL',
    'STRONG_WIND_WILL',
    'TABOO_REVERSE_WILL',
    'FREE_PLACEMENT',
    'LAST_RESORT',
    'EQUALITY_WILL',
    'REINFORCEMENT_WILL',
    'SUPPORT_TROOPS_WILL',
    'SNIPER_WILL',
    'HYPERACTIVE_WILL',
    'ESCAPE_WILL',
    'INSTANT_HYPERACTIVE_WILL',
    'EXTREME_HYPERACTIVE_WILL',
    'CLONE_WILL',
    'BOARD_EXPANSION_WILL',
    'BOARD_EXPANSION_GOD',
    'BOARD_SHRINK_WILL',
    'BOARD_SHRINK_GOD',
    'METEOR_WILL',
    'METEOR_GOD',
    'TELEPORT_WILL',
    'CELL_TELEPORT_WILL',
    'RIBO_WILL',
    'LOSS_WILL',
    'CORROSION_WILL',
    'BUOYANCY_WILL',
    'SUPER_BUOYANCY_WILL',
    'GRAVITY_WILL',
    'SUPER_GRAVITY_WILL',
    'SUPER_ATTRACTION_WILL',
    'WILL_HUNTER_KING',
    'THEORY_INCARNATION',
    'SEED_WILL'
]);

const CORNER_RECOVERY_CARD_TYPES = (SharedCardHeuristics && typeof SharedCardHeuristics.createExtendedTypeSet === 'function')
    ? SharedCardHeuristics.createExtendedTypeSet(
        SharedCardHeuristics.DEFAULT_CORNER_RECOVERY_CARD_TYPES,
        [
            'CELL_TELEPORT_WILL',
            'FREE_PLACEMENT',
            'LAST_RESORT',
            'DESTROY_DRAGON_WILL',
            'LOSS_WILL',
            'BUOYANCY_WILL',
            'SUPER_BUOYANCY_WILL',
            'GRAVITY_WILL',
            'SUPER_GRAVITY_WILL',
            'SUPER_ATTRACTION_WILL'
        ]
    )
    : new Set([
        'DESTROY_ONE_STONE',
        'SWAP_WITH_ENEMY',
        'POSITION_SWAP_WILL',
        'STRONG_WIND_WILL',
        'TEMPT_WILL',
        'CAPTURE_WILL',
        'ULTIMATE_DESTROY_GOD',
        'ULTIMATE_REVERSE_DRAGON',
        'METEOR_WILL',
        'METEOR_GOD',
        'BOARD_SHRINK_WILL',
        'BOARD_SHRINK_GOD',
        'CELL_TELEPORT_WILL',
        'TABOO_REVERSE_WILL',
        'FREE_PLACEMENT',
        'LAST_RESORT',
        'DESTROY_DRAGON_WILL',
        'LOSS_WILL',
        'BUOYANCY_WILL',
        'SUPER_BUOYANCY_WILL',
        'GRAVITY_WILL',
        'SUPER_GRAVITY_WILL',
        'SUPER_ATTRACTION_WILL'
    ]);

const CORNER_HOLD_CARD_TYPES = (SharedCardHeuristics && typeof SharedCardHeuristics.createExtendedTypeSet === 'function')
    ? SharedCardHeuristics.createExtendedTypeSet(
        SharedCardHeuristics.DEFAULT_CORNER_HOLD_CARD_TYPES,
        [
            'AFTERIMAGE_WILL',
            'GHOST_WILL',
            'TRAP_WILL',
            'SNIPER_WILL',
            'LIGHTNING_WILL',
            'METEOR_GOD',
            'DESTROY_DRAGON_WILL',
            'WILL_HUNTER_KING',
            'STONE_SALVATION_GOD'
        ]
    )
    : new Set([
        'PROTECTED_NEXT_STONE',
        'GHOST_WILL',
        'PERMA_PROTECT_NEXT_STONE',
        'GUARD_WILL',
        'GUARDIAN_GOD',
        'REGEN_WILL',
        'BLOCKADE_WILL',
        'TRAP_WILL',
        'SNIPER_WILL',
        'LIGHTNING_WILL',
        'METEOR_GOD',
        'DESTROY_DRAGON_WILL',
        'WILL_HUNTER_KING',
        'STONE_SALVATION_GOD'
    ]);

const CHARGE_RAMP_CARD_TYPES = (SharedCardHeuristics && typeof SharedCardHeuristics.createExtendedTypeSet === 'function')
    ? SharedCardHeuristics.createExtendedTypeSet(
        SharedCardHeuristics.DEFAULT_CHARGE_RAMP_CARD_TYPES,
        [
            'RIBO_WILL',
        ]
    )
    : new Set([
        'TREASURE_BOX',
        'GOLD_STONE',
        'RAINBOW_STONE',
        'SILVER_STONE',
        'CRYSTAL_STONE',
        'WORK_WILL',
        'RIBO_WILL',
    ]);

const REBUILD_KEEP_PRIORITY_CARD_TYPES = new Set([
    'PROTECTED_NEXT_STONE',
    'AFTERIMAGE_WILL',
    'GHOST_WILL',
    'PERMA_PROTECT_NEXT_STONE',
    'GUARD_WILL',
    'GUARDIAN_GOD',
    'REGEN_WILL',
    'BLOCKADE_WILL',
    'EXTEND_LIFE_WILL',
    'EXTEND_LIFE_GOD',
    'DESTROY_ONE_STONE',
    'SWAP_WITH_ENEMY',
    'POSITION_SWAP_WILL',
    'STRONG_WIND_WILL',
    'FREE_PLACEMENT',
    'LAST_RESORT',
    'HEAVEN_BLESSING',
    'CONDEMN_WILL',
    'OBSERVER_WILL',
    'THEORY_INCARNATION'
]);

const STABILITY_CARD_TYPES = new Set([
    'PROTECTED_NEXT_STONE',
    'AFTERIMAGE_WILL',
    'GHOST_WILL',
    'PERMA_PROTECT_NEXT_STONE',
    'GUARD_WILL',
    'GUARDIAN_GOD',
    'REGEN_WILL',
    'BLOCKADE_WILL',
    'TRAP_WILL',
    'EXTEND_LIFE_WILL',
    'EXTEND_LIFE_GOD',
    'HEAVEN_BLESSING',
    'OBSERVER_WILL',
    'THEORY_INCARNATION',
    'SNIPER_WILL',
    'LIGHTNING_WILL',
    'METEOR_GOD',
    'WORK_WILL',
    'LIVING_WILL',
    'DESTROY_DRAGON_WILL',
    'WILL_HUNTER_KING',
    'STONE_SALVATION_GOD'
]);

const SWING_CARD_TYPES = new Set([
    'DESTROY_ONE_STONE',
    'SWAP_WITH_ENEMY',
    'POSITION_SWAP_WILL',
    'STRONG_WIND_WILL',
    'TEMPT_WILL',
    'CAPTURE_WILL',
    'ULTIMATE_DESTROY_GOD',
    'ULTIMATE_REVERSE_DRAGON',
    'TIME_BOMB',
    'CROSS_BOMB',
    'X_BOMB',
    'TABOO_REVERSE_WILL',
    'FREE_PLACEMENT',
    'LAST_RESORT',
    'EQUALITY_WILL',
    'REINFORCEMENT_WILL',
    'SUPPORT_TROOPS_WILL',
    'METEOR_WILL',
    'METEOR_GOD',
    'BOARD_SHRINK_WILL',
    'BOARD_SHRINK_GOD',
    'BOARD_EXPANSION_WILL',
    'BOARD_EXPANSION_GOD',
    'REVERSE_WILL',
    'CLONE_WILL',
    ...CHAIN_WILL_CARD_TYPES,
    'TELEPORT_WILL',
    'CELL_TELEPORT_WILL',
    'EXTREME_HYPERACTIVE_WILL',
    'LOSS_WILL',
    'CORROSION_WILL',
    'DESTROY_DRAGON_WILL',
    'BUOYANCY_WILL',
    'SUPER_BUOYANCY_WILL',
    'GRAVITY_WILL',
    'SUPER_GRAVITY_WILL'
]);

const EDGE_CONTEST_CARD_TYPES = new Set([
    'DESTROY_ONE_STONE',
    'SWAP_WITH_ENEMY',
    'POSITION_SWAP_WILL',
    'STRONG_WIND_WILL',
    'TEMPT_WILL',
    'CAPTURE_WILL',
    'TABOO_REVERSE_WILL',
    'FREE_PLACEMENT',
    'LAST_RESORT',
    'METEOR_WILL',
    'METEOR_GOD',
    'BOARD_SHRINK_WILL',
    'BOARD_SHRINK_GOD',
    'BOARD_EXPANSION_WILL',
    'BOARD_EXPANSION_GOD',
    'CLONE_WILL',
    'SNIPER_WILL',
    'BLOCKADE_WILL',
    'TELEPORT_WILL',
    'CELL_TELEPORT_WILL',
    'EXTREME_HYPERACTIVE_WILL',
    'DESTROY_DRAGON_WILL',
    'BUOYANCY_WILL',
    'SUPER_BUOYANCY_WILL',
    'GRAVITY_WILL',
    'SUPER_GRAVITY_WILL'
]);

const LONG_HORIZON_CARD_TYPES = new Set([
    'WORK_WILL',
    'SNIPER_WILL',
    'LIGHTNING_WILL',
    'METEOR_GOD',
    'BOARD_EXPANSION_WILL',
    'BOARD_EXPANSION_GOD',
    'BREEDING_WILL',
    'SEED_WILL',
    'ULTIMATE_DESTROY_GOD',
    'ULTIMATE_REVERSE_DRAGON',
    'ULTIMATE_HYPERACTIVE_GOD',
    'TIME_STOP_GOD',

    'TIME_STOP_DEITY',
    'RIBO_WILL',
    'ROBOT_VACUUM_WILL',
    'DESTROY_DRAGON_WILL',
    'THEORY_INCARNATION',
    'EXTREME_HYPERACTIVE_WILL',
    'GLUTTONOUS_WILL',
    'WILL_HUNTER_KING'
]);

const WHITE_LV6_CORNER_SWING_KEEP_TYPES = new Set([
    'SWAP_WITH_ENEMY',
    'POSITION_SWAP_WILL',
    'BOARD_EXPANSION_WILL',
    'BOARD_EXPANSION_GOD',
    'TELEPORT_WILL',
    'CELL_TELEPORT_WILL',
    'FREE_PLACEMENT',
    'LAST_RESORT',
    'BUOYANCY_WILL',
    'SUPER_BUOYANCY_WILL',
    'GRAVITY_WILL',
    'SUPER_GRAVITY_WILL'
]);

const WHITE_LV6_FAST_ROTATE_TYPES = new Set([
    ...CHAIN_WILL_CARD_TYPES,
    'DOUBLE_PLACE',
    'BREEDING_WILL',
    'CLONE_WILL',
    'ESCAPE_WILL',
    'RIBO_WILL',
    'ROBOT_VACUUM_WILL'
]);

const WHITE_LV6_DESTROY_WHEN_AHEAD_TYPES = new Set([
    'TIME_BOMB',
    'TIME_STOP_GOD',

    'TIME_STOP_DEITY',
    'LAST_RESORT',
    'DOUBLE_PLACE',
    'TRIPLE_PLACE',
    'QUAD_PLACE',
    'INFINITE_PLACE',
    ...CHAIN_WILL_CARD_TYPES,
    'CROSS_BOMB',
    'X_BOMB',
    'HYPERACTIVE_WILL',
    'INSTANT_HYPERACTIVE_WILL',
    'ULTIMATE_HYPERACTIVE_GOD',
    'ULTIMATE_REVERSE_DRAGON',
    'TABOO_REVERSE_WILL',
    'METEOR_WILL',
    'METEOR_GOD',
    'BOARD_SHRINK_WILL',
    'BOARD_SHRINK_GOD',
    'CELL_TELEPORT_WILL',
    'GLUTTONOUS_WILL',
    'TREASURE_BOX',
    'LOSS_WILL',
    'CORROSION_WILL',
    'BOARD_EXPANSION_WILL',
    'BOARD_EXPANSION_GOD',
    'BREEDING_WILL',
    'CLONE_WILL',
    'ESCAPE_WILL',
    'RIBO_WILL',
    'ROBOT_VACUUM_WILL',
    'EXTREME_HYPERACTIVE_WILL'
]);

const IMMEDIATE_DESTROY_CARD_TYPES = new Set([
    'TIME_STOP_GOD',

    'TIME_STOP_DEITY',
    'CELL_TELEPORT_WILL',
    'FREEZE_WILL'
]);

const LOW_CHARGE_DESTROY_CARD_TYPES = new Set([
    'ESCAPE_WILL',
    'BOARD_EXPANSION_GOD',
    'REVEAL_HAND_WILL',
    'FATE_WILL'
]);

const CONDITION_DEPENDENT_DESTROY_CARD_TYPES = new Set([
    'RIBO_WILL',
    'LAST_RESORT',
    'EQUALITY_WILL',
    'REINFORCEMENT_WILL',
    'SUPPORT_TROOPS_WILL',
    'CORROSION_WILL',
    'SALVATION_WILL',
    'EXECUTION_WILL'
]);

const LOW_CHARGE_DESTROY_MAX_CHARGE = 50;

export {
    CHAIN_WILL_CARD_TYPES,
    CHARGE_RAMP_CARD_TYPES,
    CONDITION_DEPENDENT_DESTROY_CARD_TYPES,
    CORNER_HOLD_CARD_TYPES,
    CORNER_RECOVERY_CARD_TYPES,
    DEFENSIVE_CARD_TYPES,
    EDGE_CONTEST_CARD_TYPES,
    HIGH_VARIANCE_CARD_TYPES,
    IMMEDIATE_DESTROY_CARD_TYPES,
    LONG_HORIZON_CARD_TYPES,
    LOW_CHARGE_DESTROY_CARD_TYPES,
    LOW_CHARGE_DESTROY_MAX_CHARGE,
    REBUILD_KEEP_PRIORITY_CARD_TYPES,
    STABILITY_CARD_TYPES,
    SWING_CARD_TYPES,
    THROW_CHAIN_CARD_TYPES,
    WHITE_LV6_CORNER_SWING_KEEP_TYPES,
    WHITE_LV6_DESTROY_WHEN_AHEAD_TYPES,
    WHITE_LV6_FAST_ROTATE_TYPES
};

module.exports = {
    CHAIN_WILL_CARD_TYPES,
    CHARGE_RAMP_CARD_TYPES,
    CONDITION_DEPENDENT_DESTROY_CARD_TYPES,
    CORNER_HOLD_CARD_TYPES,
    CORNER_RECOVERY_CARD_TYPES,
    DEFENSIVE_CARD_TYPES,
    EDGE_CONTEST_CARD_TYPES,
    HIGH_VARIANCE_CARD_TYPES,
    IMMEDIATE_DESTROY_CARD_TYPES,
    LONG_HORIZON_CARD_TYPES,
    LOW_CHARGE_DESTROY_CARD_TYPES,
    LOW_CHARGE_DESTROY_MAX_CHARGE,
    REBUILD_KEEP_PRIORITY_CARD_TYPES,
    STABILITY_CARD_TYPES,
    SWING_CARD_TYPES,
    THROW_CHAIN_CARD_TYPES,
    WHITE_LV6_CORNER_SWING_KEEP_TYPES,
    WHITE_LV6_DESTROY_WHEN_AHEAD_TYPES,
    WHITE_LV6_FAST_ROTATE_TYPES
};
