/** Canonical defaults and CLI aliases for scalar training-cycle options.
 * Cross-option validation and environment-dependent defaults remain in the cycle parser. */
type ScalarOption = Readonly<{ key: string; kind: 'number' | 'boolean'; defaultValue: number | boolean; flags: readonly string[]; negativeFlags?: readonly string[] }>;

export const TRAINING_CYCLE_SCALAR_OPTIONS = Object.freeze([
    { key: 'help', kind: 'boolean', defaultValue: false, flags: ["--help","-h"] },
    { key: 'iterations', kind: 'number', defaultValue: 1, flags: ["--iterations","-n"] },
    { key: 'maxHours', kind: 'number', defaultValue: 100, flags: ["--max-hours"] },
    { key: 'trainGames', kind: 'number', defaultValue: 20000, flags: ["--train-games"] },
    { key: 'evalGames', kind: 'number', defaultValue: 2000, flags: ["--eval-games"] },
    { key: 'selfplayResumeChunkSize', kind: 'number', defaultValue: 1000, flags: ["--selfplay-resume-chunk-size"] },
    { key: 'seed', kind: 'number', defaultValue: 1, flags: ["--seed","-s"] },
    { key: 'seedStride', kind: 'number', defaultValue: 1000, flags: ["--seed-stride"] },
    { key: 'evalSeedOffset', kind: 'number', defaultValue: 100000, flags: ["--eval-seed-offset"] },
    { key: 'maxPlies', kind: 'number', defaultValue: 220, flags: ["--max-plies"] },
    { key: 'allowCardUsage', kind: 'boolean', defaultValue: true, flags: ["--with-cards"], negativeFlags: ["--no-cards"] },
    { key: 'selfplayGenerateHardcases', kind: 'boolean', defaultValue: true, flags: ["--selfplay-hardcases"], negativeFlags: ["--no-selfplay-hardcases"] },
    { key: 'cardUsageRate', kind: 'number', defaultValue: 0.2, flags: ["--card-usage-rate"] },
    { key: 'selfplayPolicyMixRate', kind: 'number', defaultValue: 1, flags: ["--selfplay-policy-mix-rate"] },
    { key: 'selfplayPolicyModelPoolSize', kind: 'number', defaultValue: 4, flags: ["--selfplay-policy-model-pool-size"] },
    { key: 'selfplayPolicyPoolRecencyDecay', kind: 'number', defaultValue: 2.5, flags: ["--selfplay-policy-pool-recency-decay"] },
    { key: 'selfplayPolicyCurrentAnchorRate', kind: 'number', defaultValue: 0.35, flags: ["--selfplay-policy-current-anchor-rate"] },
    { key: 'selfplayCardUsageRateJitter', kind: 'number', defaultValue: 0, flags: ["--selfplay-card-usage-rate-jitter"] },
    { key: 'selfplayTacticalWeightMin', kind: 'number', defaultValue: 1, flags: ["--selfplay-tactical-weight-min"] },
    { key: 'selfplayTacticalWeightMax', kind: 'number', defaultValue: 1, flags: ["--selfplay-tactical-weight-max"] },
    { key: 'selfplayTacticalDepthOpening', kind: 'number', defaultValue: 4, flags: ["--selfplay-tactical-depth-opening"] },
    { key: 'selfplayTacticalDepthMid', kind: 'number', defaultValue: 6, flags: ["--selfplay-tactical-depth-mid"] },
    { key: 'selfplayTacticalDepthEnd', kind: 'number', defaultValue: 8, flags: ["--selfplay-tactical-depth-end"] },
    { key: 'selfplayTacticalBeamWidth', kind: 'number', defaultValue: 12, flags: ["--selfplay-tactical-beam-width"] },
    { key: 'selfplayTeacherCommitteeWeightMin', kind: 'number', defaultValue: 28, flags: ["--selfplay-teacher-committee-weight-min"] },
    { key: 'selfplayTeacherCommitteeWeightMax', kind: 'number', defaultValue: 28, flags: ["--selfplay-teacher-committee-weight-max"] },
    { key: 'selfplayTeacherCommitteeConsensusBonusMin', kind: 'number', defaultValue: 320, flags: ["--selfplay-teacher-committee-consensus-bonus-min"] },
    { key: 'selfplayTeacherCommitteeConsensusBonusMax', kind: 'number', defaultValue: 320, flags: ["--selfplay-teacher-committee-consensus-bonus-max"] },
    { key: 'selfplayPolicyScoreWeightMin', kind: 'number', defaultValue: 1, flags: ["--selfplay-policy-score-weight-min"] },
    { key: 'selfplayPolicyScoreWeightMax', kind: 'number', defaultValue: 1, flags: ["--selfplay-policy-score-weight-max"] },
    { key: 'selfplayHeuristicWeightMin', kind: 'number', defaultValue: 1, flags: ["--selfplay-heuristic-weight-min"] },
    { key: 'selfplayHeuristicWeightMax', kind: 'number', defaultValue: 1, flags: ["--selfplay-heuristic-weight-max"] },
    { key: 'onnxEpochs', kind: 'number', defaultValue: 9999, flags: ["--onnx-epochs"] },
    { key: 'onnxBatchSize', kind: 'number', defaultValue: 2048, flags: ["--onnx-batch-size"] },
    { key: 'onnxLr', kind: 'number', defaultValue: 0.001, flags: ["--onnx-lr"] },
    { key: 'onnxHiddenSize', kind: 'number', defaultValue: 256, flags: ["--onnx-hidden-size"] },
    { key: 'onnxLogIntervalSteps', kind: 'number', defaultValue: 0, flags: ["--onnx-log-interval-steps"] },
    { key: 'onnxValSplit', kind: 'number', defaultValue: 0.1, flags: ["--onnx-val-split"] },
    { key: 'onnxEarlyStopPatience', kind: 'number', defaultValue: 8, flags: ["--onnx-early-stop-patience"] },
    { key: 'onnxEarlyStopMinDelta', kind: 'number', defaultValue: 0.0005, flags: ["--onnx-early-stop-min-delta"] },
    { key: 'onnxEarlyStopMinEpochs', kind: 'number', defaultValue: 8, flags: ["--onnx-early-stop-min-epochs"] },
    { key: 'onnxEarlyStopSmoothingWindow', kind: 'number', defaultValue: 1, flags: ["--onnx-early-stop-smoothing-window"] },
    { key: 'onnxLrPlateauPatience', kind: 'number', defaultValue: 0, flags: ["--onnx-lr-plateau-patience"] },
    { key: 'onnxLrPlateauFactor', kind: 'number', defaultValue: 0.6, flags: ["--onnx-lr-plateau-factor"] },
    { key: 'onnxResumeOptimizer', kind: 'boolean', defaultValue: false, flags: ["--onnx-resume-optimizer"], negativeFlags: ["--no-onnx-resume-optimizer"] },
    { key: 'onnxCardNoActionWeight', kind: 'number', defaultValue: 0.7, flags: ["--onnx-card-no-action-weight"] },
    { key: 'onnxCardClassBalancePower', kind: 'number', defaultValue: 0.25, flags: ["--onnx-card-class-balance-power"] },
    { key: 'onnxWinnerSampleBoost', kind: 'number', defaultValue: 0.35, flags: ["--onnx-winner-sample-boost"] },
    { key: 'onnxLoserSampleWeight', kind: 'number', defaultValue: 0.8, flags: ["--onnx-loser-sample-weight"] },
    { key: 'onnxDrawSampleWeight', kind: 'number', defaultValue: 1.0, flags: ["--onnx-draw-sample-weight"] },
    { key: 'onnxCornerEmergencySampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-corner-emergency-sample-boost"] },
    { key: 'onnxNegativeFutureDiscSampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-negative-future-disc-sample-boost"] },
    { key: 'onnxNegativeFutureDiscThreshold', kind: 'number', defaultValue: -1.0, flags: ["--onnx-negative-future-disc-threshold"] },
    { key: 'onnxTacticalMissSampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-tactical-miss-sample-boost"] },
    { key: 'onnxTacticalMissThreshold', kind: 'number', defaultValue: 0.08, flags: ["--onnx-tactical-miss-threshold"] },
    { key: 'onnxHandPressureSampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-hand-pressure-sample-boost"] },
    { key: 'onnxPendingTargetSampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-pending-target-sample-boost"] },
    { key: 'onnxCornerBalanceSampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-corner-balance-sample-boost"] },
    { key: 'onnxEdgeBalanceSampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-edge-balance-sample-boost"] },
    { key: 'onnxEconomyBalanceSampleBoost', kind: 'number', defaultValue: 0.0, flags: ["--onnx-economy-balance-sample-boost"] },
    { key: 'onnxValueTargetCornerWeight', kind: 'number', defaultValue: 0.0, flags: ["--onnx-value-target-corner-weight"] },
    { key: 'onnxValueTargetEdgeWeight', kind: 'number', defaultValue: 0.0, flags: ["--onnx-value-target-edge-weight"] },
    { key: 'onnxValueTargetEconomyWeight', kind: 'number', defaultValue: 0.0, flags: ["--onnx-value-target-economy-weight"] },
    { key: 'onnxValueTargetCornerEmergencyWeight', kind: 'number', defaultValue: 0.0, flags: ["--onnx-value-target-corner-emergency-weight"] },
    { key: 'trainTargetHeadEnabled', kind: 'boolean', defaultValue: false, flags: ["--train-target-head"], negativeFlags: ["--no-train-target-head"] },
    { key: 'trainValueHeadEnabled', kind: 'boolean', defaultValue: true, flags: ["--train-value-head"], negativeFlags: ["--no-train-value-head"] },
    { key: 'trainCardEvery', kind: 'number', defaultValue: 0, flags: ["--train-card-every"] },
    { key: 'trainTargetEvery', kind: 'number', defaultValue: 1, flags: ["--train-target-every"] },
    { key: 'trainValueEvery', kind: 'number', defaultValue: 1, flags: ["--train-value-every"] },
    { key: 'minVisits', kind: 'number', defaultValue: 12, flags: ["--min-visits"] },
    { key: 'shapeImmediate', kind: 'number', defaultValue: 0.4, flags: ["--shape-immediate"] },
    { key: 'quickGames', kind: 'number', defaultValue: 500, flags: ["--quick-games"] },
    { key: 'finalGames', kind: 'number', defaultValue: 2000, flags: ["--final-games"] },
    { key: 'threshold', kind: 'number', defaultValue: 0.05, flags: ["--threshold"] },
    { key: 'adoptionSeedCount', kind: 'number', defaultValue: 1, flags: ["--adoption-seed-count"] },
    { key: 'adoptionSeedStride', kind: 'number', defaultValue: 1000, flags: ["--adoption-seed-stride"] },
    { key: 'adoptionFinalSeedOffset', kind: 'number', defaultValue: 500000, flags: ["--adoption-final-seed-offset"] },
    { key: 'adoptionConfidenceLevel', kind: 'number', defaultValue: 0.95, flags: ["--adoption-confidence-level"] },
    { key: 'adoptionMinLowerBound', kind: 'number', defaultValue: -1, flags: ["--adoption-min-lower-bound"] },
    { key: 'adoptionMinSeedUplift', kind: 'number', defaultValue: -1, flags: ["--adoption-min-seed-uplift"] },
    { key: 'adoptionMinSeedPassCount', kind: 'number', defaultValue: 0, flags: ["--adoption-min-seed-pass-count"] },
    { key: 'qualityGateEnabled', kind: 'boolean', defaultValue: false, flags: ["--quality-gate"], negativeFlags: ["--no-quality-gate"] },
    { key: 'qualityGateGames', kind: 'number', defaultValue: 1000, flags: ["--quality-gate-games"] },
    { key: 'qualityGateSeedCount', kind: 'number', defaultValue: 1, flags: ["--quality-gate-seed-count"] },
    { key: 'qualityGateSeedStride', kind: 'number', defaultValue: 1000, flags: ["--quality-gate-seed-stride"] },
    { key: 'qualityGateSeedOffset', kind: 'number', defaultValue: 250000, flags: ["--quality-gate-seed-offset"] },
    { key: 'qualityGateThreshold', kind: 'number', defaultValue: 0, flags: ["--quality-gate-threshold"] },
    { key: 'qualityGateConfidenceLevel', kind: 'number', defaultValue: 0.95, flags: ["--quality-gate-confidence-level"] },
    { key: 'qualityGateMinLowerBound', kind: 'number', defaultValue: -1, flags: ["--quality-gate-min-lower-bound"] },
    { key: 'qualityGateMinSeedUplift', kind: 'number', defaultValue: -1, flags: ["--quality-gate-min-seed-uplift"] },
    { key: 'qualityGateMinSeedPassCount', kind: 'number', defaultValue: 0, flags: ["--quality-gate-min-seed-pass-count"] },
    { key: 'qualityGateStrengthFirst', kind: 'boolean', defaultValue: false, flags: ["--quality-gate-strength-first"], negativeFlags: ["--no-quality-gate-strength-first"] },
    { key: 'quickAdoptionSeedOffset', kind: 'number', defaultValue: 0, flags: ["--quick-adoption-seed-offset"] },
    { key: 'adoptionTacticalWeight', kind: 'number', defaultValue: 0.25, flags: ["--adoption-tactical-weight"] },
    { key: 'adoptionTacticalDepthOpening', kind: 'number', defaultValue: 4, flags: ["--adoption-tactical-depth-opening"] },
    { key: 'adoptionTacticalDepthMid', kind: 'number', defaultValue: 6, flags: ["--adoption-tactical-depth-mid"] },
    { key: 'adoptionTacticalDepthEnd', kind: 'number', defaultValue: 8, flags: ["--adoption-tactical-depth-end"] },
    { key: 'adoptionTacticalBeamWidth', kind: 'number', defaultValue: 12, flags: ["--adoption-tactical-beam-width"] },
    { key: 'adoptionPolicyScoreWeight', kind: 'number', defaultValue: 2.0, flags: ["--adoption-policy-score-weight"] },
    { key: 'adoptionHeuristicWeight', kind: 'number', defaultValue: 0.85, flags: ["--adoption-heuristic-weight"] },
    { key: 'adoptionWhitePriority', kind: 'number', defaultValue: 1.0, flags: ["--adoption-white-priority"] },
    { key: 'adoptionQualityWeightCorner', kind: 'number', defaultValue: 0.22, flags: ["--adoption-quality-weight-corner"] },
    { key: 'adoptionQualityWeightEdge', kind: 'number', defaultValue: 0.10, flags: ["--adoption-quality-weight-edge"] },
    { key: 'adoptionQualityWeightCornerRecovery', kind: 'number', defaultValue: 0.18, flags: ["--adoption-quality-weight-corner-recovery"] },
    { key: 'adoptionQualityWeightCornerRecapture', kind: 'number', defaultValue: 0.14, flags: ["--adoption-quality-weight-corner-recapture"] },
    { key: 'adoptionQualityWeightEdgeRecovery', kind: 'number', defaultValue: 0.12, flags: ["--adoption-quality-weight-edge-recovery"] },
    { key: 'adoptionQualityWeightCornerHold', kind: 'number', defaultValue: 0.16, flags: ["--adoption-quality-weight-corner-hold"] },
    { key: 'adoptionQualityWeightCornerHoldTurns', kind: 'number', defaultValue: 0.10, flags: ["--adoption-quality-weight-corner-hold-turns"] },
    { key: 'adoptionQualityWeightEdgeHold', kind: 'number', defaultValue: 0.09, flags: ["--adoption-quality-weight-edge-hold"] },
    { key: 'adoptionQualityWeightEdgeChain', kind: 'number', defaultValue: 0.12, flags: ["--adoption-quality-weight-edge-chain"] },
    { key: 'adoptionQualityWeightFinalCornerShare', kind: 'number', defaultValue: 0.24, flags: ["--adoption-quality-weight-final-corner-share"] },
    { key: 'adoptionQualityWeightFinalEdgeShare', kind: 'number', defaultValue: 0.06, flags: ["--adoption-quality-weight-final-edge-share"] },
    { key: 'adoptionQualityWeightFinalLongestEdgeRunShare', kind: 'number', defaultValue: 0.08, flags: ["--adoption-quality-weight-final-longest-edge-run-share"] },
    { key: 'adoptionQualityWeightCornerDonationAvoidance', kind: 'number', defaultValue: 0.14, flags: ["--adoption-quality-weight-corner-donation-avoidance"] },
    { key: 'adoptionQualityWeightOpponentSafeEdgeAvoidance', kind: 'number', defaultValue: 0.12, flags: ["--adoption-quality-weight-opponent-safe-edge-avoidance"] },
    { key: 'adoptionQualityWeightOwnSafeEdge', kind: 'number', defaultValue: 0.12, flags: ["--adoption-quality-weight-own-safe-edge"] },
    { key: 'adoptionQualityWeightOwnEdgeGapAvoidance', kind: 'number', defaultValue: 0.10, flags: ["--adoption-quality-weight-own-edge-gap-avoidance"] },
    { key: 'adoptionQualityWeightOpponentEdgeCut', kind: 'number', defaultValue: 0.08, flags: ["--adoption-quality-weight-opponent-edge-cut"] },
    { key: 'adoptionQualityWeightBonus', kind: 'number', defaultValue: 0.01, flags: ["--adoption-quality-weight-bonus"] },
    { key: 'adoptionQualityWeightCardImmediate', kind: 'number', defaultValue: 0, flags: ["--adoption-quality-weight-card-immediate"] },
    { key: 'adoptionQualityWeightCardFuture', kind: 'number', defaultValue: 0, flags: ["--adoption-quality-weight-card-future"] },
    { key: 'adoptionQualityWeightPlaceDelta', kind: 'number', defaultValue: 0.015, flags: ["--adoption-quality-weight-place-delta"] },
    { key: 'adoptionUseGuideBaseline', kind: 'boolean', defaultValue: false, flags: ["--adoption-use-guide-baseline"], negativeFlags: ["--no-adoption-use-guide-baseline"] },
    { key: 'adoptionUseAnchorBaseline', kind: 'boolean', defaultValue: false, flags: ["--adoption-use-anchor-baseline"], negativeFlags: ["--no-adoption-use-anchor-baseline"] },
    { key: 'onnxGateEnabled', kind: 'boolean', defaultValue: false, flags: ["--onnx-gate"], negativeFlags: ["--no-onnx-gate"] },
    { key: 'onnxGateGames', kind: 'number', defaultValue: 8, flags: ["--onnx-gate-games"] },
    { key: 'onnxGateSeedCount', kind: 'number', defaultValue: 1, flags: ["--onnx-gate-seed-count"] },
    { key: 'onnxGateSeedStride', kind: 'number', defaultValue: 1000, flags: ["--onnx-gate-seed-stride"] },
    { key: 'onnxGateSeedOffset', kind: 'number', defaultValue: 700000, flags: ["--onnx-gate-seed-offset"] },
    { key: 'onnxGateThreshold', kind: 'number', defaultValue: 0.5, flags: ["--onnx-gate-threshold"] },
    { key: 'onnxGateMinSeedScore', kind: 'number', defaultValue: 0, flags: ["--onnx-gate-min-seed-score"] },
    { key: 'onnxGateMinSeedPassCount', kind: 'number', defaultValue: 0, flags: ["--onnx-gate-min-seed-pass-count"] },
    { key: 'onnxGateMaxAverageLatencyMs', kind: 'number', defaultValue: 0, flags: ["--onnx-gate-max-average-latency-ms"] },
    { key: 'onnxGateMaxP95LatencyMs', kind: 'number', defaultValue: 0, flags: ["--onnx-gate-max-p95-latency-ms"] },
    { key: 'onnxGateMaxMaxLatencyMs', kind: 'number', defaultValue: 0, flags: ["--onnx-gate-max-max-latency-ms"] },
    { key: 'onnxGateTimeoutMs', kind: 'number', defaultValue: 180000, flags: ["--onnx-gate-timeout-ms"] },
    { key: 'onnxGateBlackLevel', kind: 'number', defaultValue: 6, flags: ["--onnx-gate-black-level"] },
    { key: 'onnxGateWhiteLevel', kind: 'number', defaultValue: 6, flags: ["--onnx-gate-white-level"] },
    { key: 'onnxPrimaryMaxQuickRegression', kind: 'number', defaultValue: 0.05, flags: ["--onnx-primary-max-quick-regression"] },
    { key: 'onnxPrimaryRequireQuickRegression', kind: 'boolean', defaultValue: false, flags: ["--onnx-primary-require-quick-regression"], negativeFlags: ["--no-onnx-primary-require-quick-regression"] },
    { key: 'onnxPrimaryRequireQuickNonRegression', kind: 'boolean', defaultValue: false, flags: ["--onnx-primary-require-quick-non-regression"], negativeFlags: ["--no-onnx-primary-require-quick-non-regression"] },
    { key: 'onnxPrimaryMinQuickCoreDelta', kind: 'number', defaultValue: 0.0, flags: ["--onnx-primary-min-quick-core-delta"] },
    { key: 'onnxPrimaryMinQuickWhiteDelta', kind: 'number', defaultValue: 0.0, flags: ["--onnx-primary-min-quick-white-delta"] },
    { key: 'onnxPrimaryMinQuickQualityDelta', kind: 'number', defaultValue: -0.01, flags: ["--onnx-primary-min-quick-quality-delta"] },
    { key: 'onnxPrimaryMinQuickUplift', kind: 'number', defaultValue: 0.0, flags: ["--onnx-primary-min-quick-uplift"] },
    { key: 'onnxPrimaryMinQuickLowerBound', kind: 'number', defaultValue: -1.0, flags: ["--onnx-primary-min-quick-lower-bound"] },
    { key: 'onnxPrimaryMinOnnxGateAvg', kind: 'number', defaultValue: 0.0, flags: ["--onnx-primary-min-onnx-gate-avg"] },
    { key: 'onnxPrimaryMinOnnxGateMinSeed', kind: 'number', defaultValue: 0.0, flags: ["--onnx-primary-min-onnx-gate-min-seed"] },
    { key: 'gateFinalIterationOnly', kind: 'boolean', defaultValue: false, flags: ["--gate-final-iteration-only"], negativeFlags: ["--no-gate-final-iteration-only"] },
    { key: 'promoteOnPass', kind: 'boolean', defaultValue: true, flags: ["--promote"], negativeFlags: ["--no-promote"] },
    { key: 'deployPromotedToRoot', kind: 'boolean', defaultValue: false, flags: ["--deploy-promoted-to-root"], negativeFlags: ["--no-deploy-promoted-to-root"] },
    { key: 'deployPromotedMinStates', kind: 'number', defaultValue: 0, flags: ["--deploy-promoted-min-states"] },
    { key: 'deployPromotedForce', kind: 'boolean', defaultValue: false, flags: ["--deploy-promoted-force"], negativeFlags: ["--no-deploy-promoted-force"] },
    { key: 'reuseExistingArtifacts', kind: 'boolean', defaultValue: false, flags: ["--reuse-existing-artifacts"] },
    { key: 'verbose', kind: 'boolean', defaultValue: false, flags: ["--verbose"] },
] as const satisfies readonly ScalarOption[]);

const optionsByFlag = new Map<string, { option: ScalarOption; enabled: boolean }>();
for (const option of TRAINING_CYCLE_SCALAR_OPTIONS as readonly ScalarOption[]) {
    for (const flag of option.flags) optionsByFlag.set(flag, { option, enabled: true });
    for (const flag of option.negativeFlags || []) optionsByFlag.set(flag, { option, enabled: false });
}

type ScalarDefaults = { [O in typeof TRAINING_CYCLE_SCALAR_OPTIONS[number] as O['key']]: O['kind'] extends 'number' ? number : boolean };

export function createTrainingCycleScalarDefaults(): ScalarDefaults {
    return Object.fromEntries(TRAINING_CYCLE_SCALAR_OPTIONS.map(option => [option.key, option.defaultValue])) as ScalarDefaults;
}

export function applyTrainingCycleScalarOption(args: Record<string, unknown>, argv: readonly string[], index: number): number | null {
    const matched = optionsByFlag.get(argv[index]);
    if (!matched) return null;
    args[matched.option.key] = matched.option.kind === 'number' ? Number(argv[index + 1]) : matched.enabled;
    return index + (matched.option.kind === 'number' ? 1 : 0);
}
