/**
 * Builds public/module-registry.js from dist/ files.
 * Run: node dist/scripts/build-module-registry.js
 * Or via tsc + node.
 */
import * as fs from 'fs';
import * as path from 'path';

declare const __non_webpack_require__: NodeRequire | undefined;

const _require: NodeRequire = (typeof __non_webpack_require__ !== 'undefined')
    ? __non_webpack_require__
    : require;

const ROOT = process.cwd();
const DIST = path.join(ROOT, 'dist');
const OUT = path.join(ROOT, 'public', 'module-registry.js');

const BROWSER_MODULE_PREFIXES = [
    'cards/',
    'constants/',
    'data/dialogue/',
    'game/',
    'shared/',
    'ui/',
    'utils/'
];

const BROWSER_ROOT_MODULES = new Set([
    'card-system.js',
    'config.js',
    'core.js',
    'cpu.js',
    'deck-builder.js',
    'dom-utils.js',
    'error-handler.js',
    'game-events.js',
    'game-state.js',
    'is-env-capable.js',
    'main.js',
    'player.js',
    'prng.js',
    'shared-constants.js',
    'sound-engine.js',
    'state.js',
    'storage.js',
    'ui.js'
]);

const DIST_EXCLUDED_BROWSER_MODULES = new Set([
    'shared/observation-gacha-catalog.generated.js',
    'shared/gacha-hand-catalog.generated.js'
]);

const EXTRA_BROWSER_MODULES: Array<{ source: string; key: string; aliases?: string[] }> = [
    { source: 'utils/owner-helpers.js', key: 'legacy/utils/owner-helpers' },
    { source: 'game/logic/cards/breeding.js', key: 'legacy/game/logic/cards/breeding' },
    { source: 'game/logic/cards/sniper.js', key: 'legacy/game/logic/cards/sniper' },
    { source: 'game/logic/cards/lightning.js', key: 'legacy/game/logic/cards/lightning' },
    { source: 'game/logic/cards/destroy_dragon.js', key: 'legacy/game/logic/cards/destroy_dragon' },
    {
        source: 'shared/observation-gacha-catalog.generated.js',
        key: 'shared/observation-gacha-catalog.generated',
        aliases: ['shared/observation-gacha-catalog.generated.js']
    },
    {
        source: 'shared/gacha-hand-catalog.generated.js',
        key: 'shared/gacha-hand-catalog.generated',
        aliases: ['shared/gacha-hand-catalog.generated.js']
    },
    {
        source: 'data/dialogue/fixed-commentary-data.js',
        key: 'data/dialogue/fixed-commentary-data',
        aliases: ['data/dialogue/fixed-commentary-data.js']
    },
    {
        source: 'game/card-effects-applier.js',
        key: 'game/card-effects-applier',
        aliases: ['game/card-effects-applier.js']
    }
];

function isBrowserModule(rel: string): boolean {
    if (rel.startsWith('dist/') || rel.startsWith('worker-public/')) return false;
    if (rel.includes('/src/types/')) return false;
    if (rel.includes('__tests__')) return false;
    if (rel.includes('.test.')) return false;
    if (DIST_EXCLUDED_BROWSER_MODULES.has(rel)) return false;
    if (BROWSER_ROOT_MODULES.has(rel)) return true;
    return BROWSER_MODULE_PREFIXES.some(prefix => rel.startsWith(prefix));
}

function walkDir(dir: string, base: string, files: string[]): void {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walkDir(full, base, files);
        } else if (entry.isFile() && entry.name.endsWith('.js')) {
            const rel = path.relative(base, full).replace(/\\/g, '/');
            files.push(rel);
        }
    }
}

function appendRegisteredModule(lines: string[], moduleKey: string, content: string): void {
    const moduleDir = path.posix.dirname(moduleKey);
    const cjsDir = moduleDir === '.' ? '' : moduleDir;
    let transformed = content
        .replace(/(?:const|let|var)\s+_require\s*=\s*\(?typeof\s+__non_webpack_require__[\s\S]*?:\s*require\s*\)?\s*;?\s*/g, '');
    transformed = 'var __cjsDir=' + JSON.stringify(cjsDir) + ';var _require=function(id){return window.require(id,__cjsDir);};var require=_require;var __require=_require;\n' + transformed;
    const jsonEncoded = JSON.stringify(transformed);
    lines.push('  _r(' + JSON.stringify(moduleKey) + ', ' + jsonEncoded + ');');
    lines.push('');
}

function appendRegisteredModuleWithJsAlias(lines: string[], moduleKey: string, content: string): void {
    appendRegisteredModule(lines, moduleKey, content);
    if (!moduleKey.endsWith('.js')) {
        appendRegisteredModule(lines, moduleKey + '.js', content);
    }
}

function buildRegistry(): void {
    const jsFiles: string[] = [];
    walkDir(DIST, DIST, jsFiles);

    const lines: string[] = [
        '// Auto-generated module registry. Do not edit.',
        '// Generated by scripts/build-module-registry.ts',
        '(function() {',
        '  var _r = window.__cjsRegister;',
        '  if (!_r) throw new Error("[cjs] runtime.js must load before module-registry.js");',
        ''
    ];

    const skipped: string[] = [];

    for (const rel of jsFiles) {
        if (!isBrowserModule(rel)) {
            skipped.push(rel + ' (non-browser)');
            continue;
        }

        const fullPath = path.join(DIST, rel);
        let content: string;
        try {
            content = fs.readFileSync(fullPath, 'utf8');
        } catch {
            skipped.push(rel);
            continue;
        }

        // Skip empty or trivial files
        if (content.trim().length === 0) {
            skipped.push(rel + ' (empty)');
            continue;
        }

        // Module key is the relative path without .js extension
        const moduleKey = rel.replace(/\.js$/, '');

        appendRegisteredModuleWithJsAlias(lines, moduleKey, content);
    }

    for (const extra of EXTRA_BROWSER_MODULES) {
        const fullPath = path.join(ROOT, extra.source);
        let content: string;
        try {
            content = fs.readFileSync(fullPath, 'utf8');
        } catch {
            skipped.push(extra.source + ' (missing extra)');
            continue;
        }
        appendRegisteredModule(lines, extra.key, content);
        for (const alias of extra.aliases || []) {
            appendRegisteredModule(lines, alias, content);
        }
    }

    lines.push('})();');
    lines.push('');

    fs.writeFileSync(OUT, lines.join('\n'), 'utf8');

    console.log('[module-registry] wrote ' + jsFiles.length + ' modules to ' + path.relative(ROOT, OUT));
    if (skipped.length > 0) {
        console.log('[module-registry] skipped ' + skipped.length + ' files:');
        skipped.forEach(s => {
            console.log('  - ' + s);
        });
    }
}

if (require.main === module) {
    buildRegistry();
}

export = {
    buildRegistry
};
