/**
 * Builds public/module-registry.js from dist/ files.
 * Run: node dist/scripts/build-module-registry.js
 * Or via tsc + node.
 */
import * as fs from 'fs';
import * as path from 'path';

declare const __non_webpack_require__: NodeRequire | undefined;

const _require: NodeRequire = (typeof __non_webpack_require__ !== 'undefined')
    ? __non_webpack_require__
    : require;

const ROOT = process.cwd();
const DIST = path.join(ROOT, 'dist');
const OUT = path.join(ROOT, 'public', 'module-registry.js');

const BROWSER_MODULE_PREFIXES = [
    'cards/',
    'constants/',
    'data/dialogue/',
    'game/',
    'shared/',
    'ui/',
    'utils/'
];

const BROWSER_ROOT_MODULES = new Set([
    'card-system.js',
    'config.js',
    'core.js',
    'cpu.js',
    'deck-builder.js',
    'dom-utils.js',
    'error-handler.js',
    'game-events.js',
    'game-state.js',
    'is-env-capable.js',
    'main.js',
    'player.js',
    'prng.js',
    'shared-constants.js',
    'sound-engine.js',
    'state.js',
    'storage.js',
    'ui.js'
]);

function isBrowserModule(rel: string): boolean {
    if (rel.startsWith('dist/') || rel.startsWith('worker-public/')) return false;
    if (rel.includes('/src/types/')) return false;
    if (BROWSER_ROOT_MODULES.has(rel)) return true;
    return BROWSER_MODULE_PREFIXES.some(prefix => rel.startsWith(prefix));
}

function walkDir(dir: string, base: string, files: string[]): void {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walkDir(full, base, files);
        } else if (entry.isFile() && entry.name.endsWith('.js')) {
            const rel = path.relative(base, full).replace(/\\/g, '/');
            files.push(rel);
        }
    }
}

function buildRegistry(): void {
    const jsFiles: string[] = [];
    walkDir(DIST, DIST, jsFiles);

    const lines: string[] = [
        '// Auto-generated module registry. Do not edit.',
        '// Generated by scripts/build-module-registry.ts',
        '(function() {',
        '  var _r = window.__cjsRegister;',
        '  if (!_r) throw new Error("[cjs] runtime.js must load before module-registry.js");',
        ''
    ];

    const skipped: string[] = [];

    for (const rel of jsFiles) {
        if (!isBrowserModule(rel)) {
            skipped.push(rel + ' (non-browser)');
            continue;
        }

        const fullPath = path.join(DIST, rel);
        let content: string;
        try {
            content = fs.readFileSync(fullPath, 'utf8');
        } catch {
            skipped.push(rel);
            continue;
        }

        // Skip empty or trivial files
        if (content.trim().length === 0) {
            skipped.push(rel + ' (empty)');
            continue;
        }

        // Module key is the relative path without .js extension
        const moduleKey = rel.replace(/\.js$/, '');

        // Remove all `_require` alias declarations — some dist files have duplicates
        // (concatenated shim + compiled code). We inject a single `_require` at the top
        // of each factory that resolves relative paths using __dirname.
        //
        // Patterns matched:
        //   const _require = typeof __non_webpack_require__ !== 'undefined' ? __non_webpack_require__ : require;
        //   const _require = (typeof __non_webpack_require__ !== 'undefined')
        //       ? __non_webpack_require__
        //       : require;
        let transformed = content
            .replace(/(?:const|let|var)\s+_require\s*=\s*\(?typeof\s+__non_webpack_require__[\s\S]*?:\s*require\s*\)?\s*;?\s*/g, '');
        // Inject _require and require with __dirname capture.
        // Modules compiled as CommonJS use `_require('../foo')` or `require('../foo')`
        // relative to their own location. The runtime's currentDir gets reset after
        // synchronous module loading, so lazy requires (in async functions called later)
        // need explicit __dirname resolution.
        transformed = 'var __cjsDir=typeof __dirname==="string"?__dirname:"";var _require=function(id){return window.require(id,__cjsDir);};var require=_require;var __require=_require;\n' + transformed;

        // Encode module source as JSON string for safe embedding.
        const jsonEncoded = JSON.stringify(transformed);

        lines.push('  _r(' + JSON.stringify(moduleKey) + ', ' + jsonEncoded + ');');
        lines.push('');
    }

    lines.push('})();');
    lines.push('');

    fs.writeFileSync(OUT, lines.join('\n'), 'utf8');

    console.log('[module-registry] wrote ' + jsFiles.length + ' modules to ' + path.relative(ROOT, OUT));
    if (skipped.length > 0) {
        console.log('[module-registry] skipped ' + skipped.length + ' files:');
        skipped.forEach(s => console.log('  - ' + s));
    }
}

if (require.main === module) {
    buildRegistry();
}
