import * as crypto from 'crypto';
import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

type CommandRunner = (command: string, args: string[]) => string;

interface CaptureRefactorBaselineOptions {
  repoRoot: string;
  outputPath: string;
  runCommand?: CommandRunner;
  pythonExecutablePath?: string;
}

const SOURCE_AUTHORITY_PATHS = [
  'game/visual-effects-map.runtime.js',
  'game/network-turn-handoff.runtime.js',
  'src/engine/selfplay-runner.ts',
  'training/engine/selfplay-runner.ts'
];

function resolveCommandExecutable(command: string): string {
  return process.platform === 'win32' && command === 'npm' ? 'npm.cmd' : command;
}

function requiresCommandShell(command: string): boolean {
  return process.platform === 'win32' && command === 'npm';
}

function resolveRepositoryRoot(currentDirectory: string): string {
  const resolvedDirectory = path.resolve(currentDirectory);
  return path.basename(path.dirname(resolvedDirectory)) === 'dist'
    ? path.resolve(resolvedDirectory, '..', '..')
    : path.resolve(resolvedDirectory, '..');
}

function commandExecutionOptions(repoRoot: string) {
  return {
    cwd: repoRoot,
    encoding: 'utf8' as const,
    stdio: ['ignore', 'pipe', 'pipe'] as ['ignore', 'pipe', 'pipe'],
    maxBuffer: 64 * 1024 * 1024
  };
}

function runCommandInRepo(repoRoot: string): CommandRunner {
  return (command, args) => {
    const options = commandExecutionOptions(repoRoot);
    if (requiresCommandShell(command)) {
      const commandLine = [resolveCommandExecutable(command), ...args].join(' ');
      return execFileSync(process.env.ComSpec || 'cmd.exe', ['/d', '/s', '/c', commandLine], options).toString();
    }
    return execFileSync(resolveCommandExecutable(command), args, options).toString();
  };
}

function countNonEmptyLines(value: string): number {
  return value.split(/\r?\n/).filter((line) => line.trim().length > 0).length;
}

function parseLogicalTreeBytes(value: string): number {
  return value.split(/\r?\n/).reduce((total, line) => {
    const match = line.match(/\s(\d+)\t/);
    return total + (match ? Number(match[1]) : 0);
  }, 0);
}

function sha256File(filePath: string): string {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

function renderSourceAuthorityInventory(repoRoot: string): string[] {
  return SOURCE_AUTHORITY_PATHS.map((relativePath) => {
    const state = fs.existsSync(path.join(repoRoot, relativePath)) ? 'present' : 'absent';
    return `- \`${relativePath}\`: ${state}`;
  });
}

function buildBaselineMarkdown(options: CaptureRefactorBaselineOptions): string {
  const repoRoot = path.resolve(options.repoRoot);
  const runCommand = options.runCommand || runCommandInRepo(repoRoot);
  const packageLockPath = path.join(repoRoot, 'package-lock.json');
  const pythonExecutablePath = options.pythonExecutablePath || path.join(repoRoot, '.venv', 'Scripts', 'python.exe');
  const startingCommit = runCommand('git', ['rev-parse', 'HEAD']).trim();
  const gitObjectStatistics = runCommand('git', ['count-objects', '-vH']).trim();
  const trackedArtifactPaths = runCommand('git', ['ls-files', 'artifacts']);
  const artifactTree = runCommand('git', ['ls-tree', '-r', '-l', 'HEAD', '--', 'artifacts']);
  const nodeVersion = runCommand('node', ['--version']).trim();
  const npmVersion = runCommand('npm', ['--version']).trim();
  const pythonVersion = fs.existsSync(pythonExecutablePath)
    ? runCommand(pythonExecutablePath, ['--version']).trim()
    : 'unavailable';
  const packageLockHash = fs.existsSync(packageLockPath) ? sha256File(packageLockPath) : 'missing';

  return [
    '# Behavior-Preserving Refactor Baseline',
    '',
    'This file is generated by `scripts/capture-refactor-baseline.ts`. It records metadata only; it does not include artifact paths or artifact contents.',
    '',
    '## Environment',
    '',
    `- Starting commit: \`${startingCommit}\``,
    `- Node: \`${nodeVersion}\``,
    `- npm: \`${npmVersion}\``,
    `- Python: ${pythonVersion === 'unavailable' ? 'unavailable' : `\`${pythonVersion}\``}`,
    `- package-lock SHA-256: \`${packageLockHash}\``,
    '',
    '## Repository Storage',
    '',
    `- Tracked artifact files: ${countNonEmptyLines(trackedArtifactPaths)}`,
    `- Logical artifact bytes: ${parseLogicalTreeBytes(artifactTree)}`,
    '- Git object statistics:',
    '```text',
    gitObjectStatistics,
    '```',
    '',
    '## Known Source-Authority Inventory',
    '',
    ...renderSourceAuthorityInventory(repoRoot),
    ''
  ].join('\n');
}

function captureRefactorBaseline(options: CaptureRefactorBaselineOptions): string {
  const outputPath = path.resolve(options.outputPath);
  const markdown = buildBaselineMarkdown(options);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, markdown, 'utf8');
  return markdown;
}

function readOutputPathFromArgs(args: string[]): string {
  const outputIndex = args.indexOf('--output');
  const outputPath = outputIndex >= 0 ? args[outputIndex + 1] : null;
  if (!outputPath) {
    throw new Error('Usage: node scripts/capture-refactor-baseline.js --output <path>');
  }
  return outputPath;
}

function main(): void {
  const repoRoot = resolveRepositoryRoot(__dirname);
  const outputPath = readOutputPathFromArgs(process.argv.slice(2));
  captureRefactorBaseline({ repoRoot, outputPath });
  console.log(`[capture-refactor-baseline] wrote ${path.relative(repoRoot, path.resolve(outputPath))}`);
}

export = {
  buildBaselineMarkdown,
  captureRefactorBaseline,
  main,
  parseLogicalTreeBytes,
  resolveCommandExecutable,
  requiresCommandShell,
  resolveRepositoryRoot,
  commandExecutionOptions
};
