"use strict";

const DEFAULT_OTHELLO_ONNX_LOOP_ARGS = {
  sessionTag: "",
  iterations: 999,
  trainGames: 1024,
  evalGames: 128,
  jobs: 8,
  datasetMaxRecords: 200000,
  replayWindow: 4,
  hardcaseReplayWindow: 4,
  hardcaseReplayWeight: 3,
  hardcaseMaxRecords: 20000,
  epochs: 18,
  batchSize: 1024,
  hiddenDim: 384,
  depth: 5,
  dropout: 0.04,
  valueLossWeight: 0.5,
  policyLossWeight: 1.0,
  whiteSampleWeight: 3.2,
  blackSampleWeight: 1,
  gatePairs: 16,
  gateOpeningPlies: 8,
  gateMinWhitePointRate: 0.55,
  gateMinWhiteDiscDiff: 0,
  championGatePairs: 16,
  championGateMinPointRate: 0.525,
  championGateMinWhitePointRate: 0.55,
  championGateMinWhiteDiscDiff: 0,
  heuristicRerankWeight: 3.0,
  policyWeight: 0.75,
  topK: 8,
  whiteSafetyMultiplier: 1.45,
  seed: 260524,
  openingPliesMin: 2,
  openingPliesMax: 10,
  openingPreferredPlayer: "white",
  openingPreferredPlayerRate: 1,
  openingSeedBankPath: "",
  openingSeedBankSampleRate: 0.7,
  depthOpening: 2,
  depthMid: 2,
  depthEnd: 3,
  exactSolveEmpties: 8,
  explorationOpening: 0.1,
  explorationMid: 0.04,
  explorationEnd: 0,
  runtimeModelOut: "data/models/othello/policy-value.onnx",
  runtimeMetaOut: "data/models/othello/policy-value.onnx.meta.json",
  championModelOut: "othello-ai/data/models/policy-value.onnx.champion.onnx",
  championMetaOut: "othello-ai/data/models/policy-value.onnx.champion.onnx.meta.json",
  initOnnx: "",
  policyTable: "othello-ai/data/models/policy-table.champion.json",
  valueTable: "othello-ai/data/models/value-table.champion.json",
  baseline: "heuristic",
  profile: "",
  preflight: false,
  help: false
};

export {
  DEFAULT_OTHELLO_ONNX_LOOP_ARGS
};
