"use strict";

const DEFAULT_OTHELLO_ONNX_LOOP_ARGS = {
  sessionTag: "",
  iterations: 999,
  trainGames: 2048,
  evalGames: 256,
  jobs: 8,
  datasetMaxRecords: 240000,
  replayWindow: 4,
  hardcaseReplayWindow: 4,
  hardcaseReplayWeight: 3,
  hardcaseMaxRecords: 20000,
  epochs: 16,
  batchSize: 1024,
  hiddenDim: 896,
  depth: 6,
  dropout: 0.04,
  valueLossWeight: 0.8,
  policyLossWeight: 1.0,
  whiteSampleWeight: 1,
  blackSampleWeight: 1,
  gatePairs: 24,
  gateOpeningPlies: 8,
  gateMinPointRate: 0.53,
  gateMinBlackPointRate: 0.5,
  gateMinWhitePointRate: 0.5,
  gateMinBlackDiscDiff: 0,
  gateMinWhiteDiscDiff: 0,
  championGatePairs: 24,
  championGateMinPointRate: 0.53,
  championGateMinBlackPointRate: 0.5,
  championGateMinWhitePointRate: 0.5,
  championGateMinBlackDiscDiff: 0,
  championGateMinWhiteDiscDiff: 0,
  maxOnnxBytes: 25 * 1024 * 1024,
  heuristicRerankWeight: 3.0,
  policyWeight: 0.75,
  topK: 8,
  whiteSafetyMultiplier: 1.0,
  seed: 260524,
  openingPliesMin: 2,
  openingPliesMax: 10,
  openingPreferredPlayer: "",
  openingPreferredPlayerRate: 0,
  openingSeedBankPath: "",
  openingSeedBankSampleRate: 0.7,
  depthOpening: 2,
  depthMid: 3,
  depthEnd: 4,
  exactSolveEmpties: 8,
  explorationOpening: 0.1,
  explorationMid: 0.04,
  explorationEnd: 0,
  runtimeModelOut: "data/models/othello/policy-value.onnx",
  runtimeMetaOut: "data/models/othello/policy-value.onnx.meta.json",
  championModelOut: "othello-ai/data/models/policy-value.onnx.champion.onnx",
  championMetaOut: "othello-ai/data/models/policy-value.onnx.champion.onnx.meta.json",
  initOnnx: "",
  policyTable: "othello-ai/data/models/policy-table.champion.json",
  valueTable: "othello-ai/data/models/value-table.champion.json",
  baseline: "heuristic",
  profile: "",
  preflight: false,
  help: false
};

export {
  DEFAULT_OTHELLO_ONNX_LOOP_ARGS
};
