// Records the short card demo videos shown from the hand card play button.
//
//   npm run build:ts && node dist/scripts/record-card-demo-videos.js [--cards id,id] [--parallel 3] [--seed 11]
//   node dist/scripts/record-card-demo-videos.js --catalog-only
//   node dist/scripts/record-card-demo-videos.js --reencode [--cards id,id]
//
// Requires the normal local server (npm run serve on http://127.0.0.1:8000/), ffmpeg/ffprobe on PATH,
// and Playwright Chromium. Output: assets/videos/cards/<cardId>.mp4 and cards/card-demo-videos.generated.ts.
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { spawn } from 'child_process';
import { Recorder, setupMidgame } from './card-demo-videos/recorder';
import { encodeClip } from './card-demo-videos/encoder';
import { SCENARIOS, SPECIAL_CARD_IDS, cropForCard, runScenario } from './card-demo-videos/scenarios';

const ROOT = path.resolve(__dirname, __dirname.includes(`${path.sep}dist${path.sep}`) ? '../..' : '..');
const VIDEO_DIR = path.join(ROOT, 'assets', 'videos', 'cards');
const CATALOG_OUT = path.join(ROOT, 'cards', 'card-demo-videos.generated.ts');
const OUT_WIDTH = 440;

function readArg(name: string): string | null {
    const i = process.argv.indexOf(name);
    return i >= 0 && i + 1 < process.argv.length ? process.argv[i + 1] : null;
}

function normalCardIds(): string[] {
    const catalog = JSON.parse(fs.readFileSync(path.join(ROOT, 'cards', 'catalog.json'), 'utf8'));
    const list: any[] = Array.isArray(catalog) ? catalog : (catalog.cards || Object.values(catalog));
    return list.map((c) => String(c.id)).filter((id) => !SPECIAL_CARD_IDS.has(id));
}

export function writeVideoCatalog(): string[] {
    const known = normalCardIds();
    const ids = known.filter((id) => fs.existsSync(path.join(VIDEO_DIR, `${id}.mp4`)));
    const body = [
        '// Auto-generated by scripts/record-card-demo-videos.ts - do not edit directly.',
        '// Card ids that have a demo video at assets/videos/cards/<id>.mp4 (special cards excluded).',
        'export const CARD_DEMO_VIDEO_IDS: readonly string[] = Object.freeze([',
        ...ids.map((id) => `    ${JSON.stringify(id)},`),
        ']);',
        ''
    ].join('\n');
    fs.writeFileSync(CATALOG_OUT, body, 'utf8');
    return ids;
}

async function recordOne(cardId: string, workRoot: string, seed: number, reencode: boolean) {
    const outDir = path.join(workRoot, cardId);
    const outFile = path.join(VIDEO_DIR, `${cardId}.mp4`);
    const crop = cropForCard(cardId);
    if (reencode) {
        const meta = JSON.parse(fs.readFileSync(path.join(outDir, 'meta.json'), 'utf8'));
        return encodeClip({ outDir, frames: meta.frames, segs: meta.segs }, outFile, { crop, outW: OUT_WIDTH });
    }
    const rec = new Recorder(outDir);
    await rec.open(seed);
    try {
        await setupMidgame(rec, 30);
        await runScenario(rec, cardId);
    } finally {
        await rec.close();
    }
    fs.writeFileSync(path.join(outDir, 'meta.json'), JSON.stringify({ frames: rec.frames, segs: rec.segs }));
    return encodeClip(rec, outFile, { crop, outW: OUT_WIDTH });
}

function runChild(cardId: string, args: string[]): Promise<{ ok: boolean; out: string }> {
    return new Promise((resolve) => {
        const child = spawn(process.execPath, [__filename, '--single', cardId, ...args], { cwd: ROOT });
        let out = '';
        child.stdout.on('data', (d) => { out += d; });
        child.stderr.on('data', (d) => { out += d; });
        const timer = setTimeout(() => child.kill(), 5 * 60 * 1000);
        child.on('close', (code) => { clearTimeout(timer); resolve({ ok: code === 0, out: out.trim() }); });
    });
}

async function main() {
    if (process.argv.includes('--catalog-only')) {
        console.log(`[card-demo-videos] catalog: ${writeVideoCatalog().length} cards`);
        return;
    }
    const seed = Number(readArg('--seed') || 11);
    const workRoot = readArg('--work') || path.join(os.tmpdir(), 'card-demo-videos');
    const reencode = process.argv.includes('--reencode');
    const single = readArg('--single');
    fs.mkdirSync(VIDEO_DIR, { recursive: true });
    if (single) {
        const r = await recordOne(single, workRoot, seed, reencode);
        console.log(`${single} ${r.seconds.toFixed(2)}s ${r.kb}KB`);
        return;
    }
    const requested = (readArg('--cards') || '').split(',').map((s) => s.trim()).filter(Boolean);
    const ids = (requested.length ? requested : normalCardIds()).filter((id) => {
        if (SPECIAL_CARD_IDS.has(id)) return false;
        if (!SCENARIOS[id]) { console.warn(`[card-demo-videos] no scenario: ${id}`); return false; }
        return true;
    });
    const parallel = Math.max(1, Number(readArg('--parallel') || 2));
    const childArgs = ['--seed', String(seed), '--work', workRoot, ...(reencode ? ['--reencode'] : [])];
    const failed: string[] = [];
    let next = 0;
    const worker = async () => {
        while (next < ids.length) {
            const id = ids[next++];
            const r = await runChild(id, childArgs);
            console.log(`${r.ok ? 'OK  ' : 'FAIL'} ${r.out.split('\n').slice(-1)[0]}`);
            if (!r.ok) failed.push(id);
        }
    };
    await Promise.all(Array.from({ length: parallel }, worker));
    const listed = writeVideoCatalog();
    console.log(`[card-demo-videos] recorded ${ids.length - failed.length}/${ids.length}; catalog lists ${listed.length} cards`);
    if (failed.length) {
        console.log(`[card-demo-videos] failed: ${failed.join(',')}`);
        process.exitCode = 1;
    }
}

if (require.main === module) {
    main().catch((error) => { console.error('[card-demo-videos] failed:', error && error.message ? error.message : error); process.exit(1); });
}
