import * as fs from 'fs';
import * as path from 'path';
import sharp from 'sharp';
import {
  analyzeLosslessWebp,
  materializeLosslessWebp
} from './lossless-webp-pipeline';

const ROOT = path.resolve(__dirname, '..', '..', '..');
const BACKGROUND_DIR = path.join(ROOT, 'assets', 'images', 'background');
const MANIFEST_PATH = path.join(BACKGROUND_DIR, 'optimized-backgrounds.json');
const GENERATED_MODULE_PATH = path.join(ROOT, 'ui', 'assets', 'optimized-backgrounds.generated.ts');
const MIN_SOURCE_BYTES = Math.floor(1.25 * 1024 * 1024);
const MIN_SAVED_BYTES = 256 * 1024;
const MIN_SAVINGS_RATIO = 0.15;
const UI_IMAGE_POLICY_PATH = path.join(ROOT, 'scripts', 'assets', 'optimized-ui-images.policy.json');

type ManifestEntry = {
  source: string;
  output: string;
  width: number;
  height: number;
  sourceBytes: number;
  outputBytes: number;
  savedBytes: number;
  sourceSha256: string;
  outputSha256: string;
};

function walkPngFiles(directory: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const fullPath = path.join(directory, entry.name);
      if (entry.isDirectory()) return walkPngFiles(fullPath);
      return entry.isFile() && entry.name.toLowerCase().endsWith('.png') ? [fullPath] : [];
    })
    .sort((left, right) => left.localeCompare(right, 'ja'));
}

function browserPath(filePath: string): string {
  return path.relative(ROOT, filePath).split(path.sep).join('/');
}

async function getCandidates(): Promise<string[]> {
  const candidates: string[] = [];
  for (const filePath of walkPngFiles(BACKGROUND_DIR)) {
    if (fs.statSync(filePath).size < MIN_SOURCE_BYTES) continue;
    const imageMetadata = await sharp(filePath).metadata();
    if (imageMetadata.hasAlpha) continue;
    candidates.push(filePath);
  }
  return candidates;
}

async function verifyEncodedOutput(
  sourcePath: string,
  outputPath: string,
  checkOnly: boolean
): Promise<ManifestEntry | null> {
  const analysis = await analyzeLosslessWebp(sourcePath);
  if (
    analysis.savedBytes < MIN_SAVED_BYTES
    || analysis.savingsRatio < MIN_SAVINGS_RATIO
  ) return null;
  materializeLosslessWebp(outputPath, analysis.encoded, checkOnly);
  return {
    source: browserPath(sourcePath),
    output: browserPath(outputPath),
    width: analysis.width,
    height: analysis.height,
    sourceBytes: analysis.sourceBytes,
    outputBytes: analysis.outputBytes,
    savedBytes: analysis.savedBytes,
    sourceSha256: analysis.sourceSha256,
    outputSha256: analysis.outputSha256
  };
}

function renderGeneratedModule(entries: ManifestEntry[]): string {
  const mapping = Object.fromEntries(entries.map((entry) => [entry.source, entry.output]));
  return [
    '// Generated by scripts/assets/build-background-images.ts. Do not edit.',
    `export const OPTIMIZED_BACKGROUND_IMAGES = Object.freeze(${JSON.stringify(mapping, null, 2)} as const);`,
    '',
    'export type OptimizedBackgroundSource = keyof typeof OPTIMIZED_BACKGROUND_IMAGES;',
    ''
  ].join('\n');
}

// Backgrounds admitted through the UI image policy (lossy start-up assets) own
// their own .webp output next to the PNG; this pipeline must not reconcile them.
function readUiImagePolicyOutputs(): Set<string> {
  try {
    const policy = JSON.parse(fs.readFileSync(UI_IMAGE_POLICY_PATH, 'utf8')) as {
      images?: Array<{ source?: string }>;
    };
    return new Set((policy.images || [])
      .map((image) => String(image.source || '').split('\\').join('/'))
      .filter((source) => source.toLowerCase().endsWith('.png'))
      .map((source) => path.resolve(ROOT, source.replace(/\.png$/i, '.webp')).toLowerCase()));
  } catch (_error) {
    return new Set();
  }
}

function reconcileGeneratedOutputs(entries: ManifestEntry[], checkOnly: boolean): void {
  const expectedOutputs = new Set(entries.map((entry) => path.resolve(ROOT, entry.output).toLowerCase()));
  readUiImagePolicyOutputs().forEach((outputPath) => expectedOutputs.add(outputPath));
  const unexpectedOutputs = fs.readdirSync(BACKGROUND_DIR, { withFileTypes: true })
    .filter((item) => item.isFile() && item.name.toLowerCase().endsWith('.webp'))
    .map((item) => path.join(BACKGROUND_DIR, item.name))
    .filter((outputPath) => {
      const sourcePath = outputPath.replace(/\.webp$/i, '.png');
      return fs.existsSync(sourcePath) && !expectedOutputs.has(path.resolve(outputPath).toLowerCase());
    });
  if (unexpectedOutputs.length === 0) return;
  if (checkOnly) {
    throw new Error(
      `unexpected generated background output(s): ${unexpectedOutputs.map(browserPath).join(', ')}`
    );
  }
  unexpectedOutputs.forEach((outputPath) => fs.unlinkSync(outputPath));
}

async function run(): Promise<void> {
  const checkOnly = process.argv.includes('--check');
  const candidates = await getCandidates();
  const entries: ManifestEntry[] = [];
  for (const sourcePath of candidates) {
    const outputPath = sourcePath.replace(/\.png$/i, '.webp');
    const entry = await verifyEncodedOutput(sourcePath, outputPath, checkOnly);
    if (entry) entries.push(entry);
  }
  reconcileGeneratedOutputs(entries, checkOnly);
  const manifest = {
    schemaVersion: 1,
    codec: 'webp-lossless',
    selection: {
      root: 'assets/images/background',
      minimumSourceBytes: MIN_SOURCE_BYTES,
      minimumSavedBytes: MIN_SAVED_BYTES,
      minimumSavingsRatio: MIN_SAVINGS_RATIO,
      pngOnly: true,
      opaqueOnly: true
    },
    images: entries,
    totals: {
      sourceBytes: entries.reduce((total, entry) => total + entry.sourceBytes, 0),
      outputBytes: entries.reduce((total, entry) => total + entry.outputBytes, 0),
      savedBytes: entries.reduce((total, entry) => total + entry.savedBytes, 0)
    }
  };
  const renderedManifest = `${JSON.stringify(manifest, null, 2)}\n`;
  const renderedModule = renderGeneratedModule(entries);
  if (checkOnly) {
    if (!fs.existsSync(MANIFEST_PATH) || fs.readFileSync(MANIFEST_PATH, 'utf8') !== renderedManifest) {
      throw new Error('optimized-backgrounds.json is stale; run npm run assets:backgrounds:build');
    }
    if (!fs.existsSync(GENERATED_MODULE_PATH) || fs.readFileSync(GENERATED_MODULE_PATH, 'utf8') !== renderedModule) {
      throw new Error('optimized-backgrounds.generated.ts is stale; run npm run assets:backgrounds:build');
    }
  } else {
    fs.writeFileSync(MANIFEST_PATH, renderedManifest, 'utf8');
    fs.mkdirSync(path.dirname(GENERATED_MODULE_PATH), { recursive: true });
    fs.writeFileSync(GENERATED_MODULE_PATH, renderedModule, 'utf8');
  }
  console.log(`Verified ${entries.length} opaque backgrounds; saved ${manifest.totals.savedBytes.toLocaleString()} bytes.`);
}

void run().catch((error) => {
  console.error(error instanceof Error ? error.stack || error.message : error);
  process.exitCode = 1;
});
