import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import sharp from 'sharp';

const ROOT = path.resolve(__dirname, '..', '..', '..');
const BACKGROUND_DIR = path.join(ROOT, 'assets', 'images', 'background');
const MANIFEST_PATH = path.join(BACKGROUND_DIR, 'optimized-backgrounds.json');
const GENERATED_MODULE_PATH = path.join(ROOT, 'ui', 'assets', 'optimized-backgrounds.generated.ts');
const MIN_SOURCE_BYTES = 2 * 1024 * 1024;

type ManifestEntry = {
  source: string;
  output: string;
  width: number;
  height: number;
  sourceBytes: number;
  outputBytes: number;
  savedBytes: number;
  sourceSha256: string;
  outputSha256: string;
};

function sha256(filePath: string): string {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

function walkPngFiles(directory: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const fullPath = path.join(directory, entry.name);
      if (entry.isDirectory()) return walkPngFiles(fullPath);
      return entry.isFile() && entry.name.toLowerCase().endsWith('.png') ? [fullPath] : [];
    })
    .sort((left, right) => left.localeCompare(right, 'ja'));
}

function browserPath(filePath: string): string {
  return path.relative(ROOT, filePath).split(path.sep).join('/');
}

async function getCandidates(): Promise<string[]> {
  const candidates: string[] = [];
  for (const filePath of walkPngFiles(BACKGROUND_DIR)) {
    if (fs.statSync(filePath).size < MIN_SOURCE_BYTES) continue;
    const imageMetadata = await sharp(filePath).metadata();
    if (imageMetadata.hasAlpha) continue;
    candidates.push(filePath);
  }
  return candidates;
}

async function buildOutput(sourcePath: string, outputPath: string): Promise<void> {
  await sharp(sourcePath, { failOn: 'error' })
    .webp({ lossless: true, effort: 6, smartSubsample: false })
    .toFile(outputPath);
}

async function verifyOutput(sourcePath: string, outputPath: string): Promise<ManifestEntry> {
  if (!fs.existsSync(outputPath)) {
    throw new Error(`missing optimized background: ${browserPath(outputPath)}`);
  }
  const [sourceMetadata, outputMetadata, sourceRaw, outputRaw] = await Promise.all([
    sharp(sourcePath).metadata(),
    sharp(outputPath).metadata(),
    sharp(sourcePath).ensureAlpha().raw().toBuffer(),
    sharp(outputPath).ensureAlpha().raw().toBuffer()
  ]);
  if (
    sourceMetadata.width !== outputMetadata.width
    || sourceMetadata.height !== outputMetadata.height
  ) {
    throw new Error(`dimension mismatch: ${browserPath(sourcePath)}`);
  }
  if (!sourceRaw.equals(outputRaw)) {
    throw new Error(`decoded RGBA mismatch: ${browserPath(sourcePath)}`);
  }
  const sourceBytes = fs.statSync(sourcePath).size;
  const outputBytes = fs.statSync(outputPath).size;
  if (outputBytes >= sourceBytes) {
    throw new Error(`lossless WebP is not smaller: ${browserPath(sourcePath)}`);
  }
  return {
    source: browserPath(sourcePath),
    output: browserPath(outputPath),
    width: sourceMetadata.width || 0,
    height: sourceMetadata.height || 0,
    sourceBytes,
    outputBytes,
    savedBytes: sourceBytes - outputBytes,
    sourceSha256: sha256(sourcePath),
    outputSha256: sha256(outputPath)
  };
}

function renderGeneratedModule(entries: ManifestEntry[]): string {
  const mapping = Object.fromEntries(entries.map((entry) => [entry.source, entry.output]));
  return [
    '// Generated by scripts/assets/build-background-images.ts. Do not edit.',
    `export const OPTIMIZED_BACKGROUND_IMAGES = Object.freeze(${JSON.stringify(mapping, null, 2)} as const);`,
    '',
    'export type OptimizedBackgroundSource = keyof typeof OPTIMIZED_BACKGROUND_IMAGES;',
    ''
  ].join('\n');
}

async function run(): Promise<void> {
  const checkOnly = process.argv.includes('--check');
  const candidates = await getCandidates();
  const entries: ManifestEntry[] = [];
  for (const sourcePath of candidates) {
    const outputPath = sourcePath.replace(/\.png$/i, '.webp');
    if (!checkOnly) await buildOutput(sourcePath, outputPath);
    entries.push(await verifyOutput(sourcePath, outputPath));
  }
  const manifest = {
    schemaVersion: 1,
    codec: 'webp-lossless',
    selection: {
      root: 'assets/images/background',
      minimumSourceBytes: MIN_SOURCE_BYTES,
      pngOnly: true,
      opaqueOnly: true
    },
    images: entries,
    totals: {
      sourceBytes: entries.reduce((total, entry) => total + entry.sourceBytes, 0),
      outputBytes: entries.reduce((total, entry) => total + entry.outputBytes, 0),
      savedBytes: entries.reduce((total, entry) => total + entry.savedBytes, 0)
    }
  };
  const renderedManifest = `${JSON.stringify(manifest, null, 2)}\n`;
  const renderedModule = renderGeneratedModule(entries);
  if (checkOnly) {
    if (!fs.existsSync(MANIFEST_PATH) || fs.readFileSync(MANIFEST_PATH, 'utf8') !== renderedManifest) {
      throw new Error('optimized-backgrounds.json is stale; run npm run assets:backgrounds:build');
    }
    if (!fs.existsSync(GENERATED_MODULE_PATH) || fs.readFileSync(GENERATED_MODULE_PATH, 'utf8') !== renderedModule) {
      throw new Error('optimized-backgrounds.generated.ts is stale; run npm run assets:backgrounds:build');
    }
  } else {
    fs.writeFileSync(MANIFEST_PATH, renderedManifest, 'utf8');
    fs.mkdirSync(path.dirname(GENERATED_MODULE_PATH), { recursive: true });
    fs.writeFileSync(GENERATED_MODULE_PATH, renderedModule, 'utf8');
  }
  console.log(`Verified ${entries.length} opaque backgrounds; saved ${manifest.totals.savedBytes.toLocaleString()} bytes.`);
}

void run().catch((error) => {
  console.error(error instanceof Error ? error.stack || error.message : error);
  process.exitCode = 1;
});
