import * as fs from 'fs';
import * as path from 'path';
import {
  analyzeLosslessWebp,
  materializeLosslessWebp
} from './lossless-webp-pipeline';

const ROOT = path.resolve(__dirname, '..', '..', '..');
const POLICY_PATH = path.join(ROOT, 'scripts', 'assets', 'optimized-ui-images.policy.json');
const MANIFEST_PATH = path.join(ROOT, 'assets', 'images', 'optimized-ui-images.json');
const GENERATED_MODULE_PATH = path.join(ROOT, 'ui', 'assets', 'optimized-ui-images.generated.ts');
const ASSET_IMAGE_ROOT = path.resolve(ROOT, 'assets', 'images');

type AdmissionStatus = 'pending-hardware' | 'admitted' | 'rejected';

interface PolicyImage {
  source: string;
  criticalPath: boolean;
  admission: {
    status: AdmissionStatus;
    reason: string;
  };
  measurement: {
    investigation: string;
    hardwareDecode: null | Readonly<Record<string, unknown>>;
  };
}

interface OptimizedUiImagePolicy {
  schemaVersion: number;
  minimumSavingsRatio: number;
  images: PolicyImage[];
}

function browserPath(filePath: string): string {
  return path.relative(ROOT, filePath).split(path.sep).join('/');
}

function readPolicy(): OptimizedUiImagePolicy {
  const policy = JSON.parse(fs.readFileSync(POLICY_PATH, 'utf8')) as OptimizedUiImagePolicy;
  if (policy.schemaVersion !== 1 || !Array.isArray(policy.images)) {
    throw new Error('optimized UI image policy schema is invalid');
  }
  if (!(policy.minimumSavingsRatio >= 0.1 && policy.minimumSavingsRatio < 1)) {
    throw new Error('optimized UI image minimumSavingsRatio must be at least 0.1');
  }
  return policy;
}

function outputPathForSource(source: string): string {
  if (!source.toLowerCase().endsWith('.png')) {
    throw new Error(`optimized UI image source must be PNG: ${source}`);
  }
  return source.replace(/\.png$/i, '.webp');
}

function renderGeneratedModule(mapping: Readonly<Record<string, string>>): string {
  return [
    '// Generated by scripts/assets/build-optimized-ui-images.ts. Do not edit.',
    `export const OPTIMIZED_UI_IMAGES = Object.freeze(${JSON.stringify(mapping, null, 2)} as const);`,
    '',
    'export type OptimizedUiImageSource = keyof typeof OPTIMIZED_UI_IMAGES;',
    ''
  ].join('\n');
}

function assertGeneratedText(
  filePath: string,
  expected: string,
  checkOnly: boolean,
  staleMessage: string
): void {
  if (checkOnly) {
    if (!fs.existsSync(filePath) || fs.readFileSync(filePath, 'utf8') !== expected) {
      throw new Error(staleMessage);
    }
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, expected, 'utf8');
}

async function run(): Promise<void> {
  const checkOnly = process.argv.includes('--check');
  const policy = readPolicy();
  const images = [];
  const admittedMapping: Record<string, string> = {};
  const seenSources = new Set<string>();

  for (const image of policy.images) {
    const source = String(image.source || '').replace(/\\/g, '/');
    const sourcePath = path.resolve(ROOT, source);
    if (
      !source.startsWith('assets/images/')
      || path.isAbsolute(source)
      || !sourcePath.startsWith(`${ASSET_IMAGE_ROOT}${path.sep}`)
    ) {
      throw new Error(`optimized UI image source is outside assets/images: ${source}`);
    }
    if (seenSources.has(source)) throw new Error(`duplicate optimized UI image source: ${source}`);
    seenSources.add(source);
    if (!['pending-hardware', 'admitted', 'rejected'].includes(image.admission?.status)) {
      throw new Error(`invalid optimized UI image admission: ${source}`);
    }
    if (!fs.existsSync(sourcePath)) throw new Error(`missing optimized UI image source: ${source}`);
    const candidateOutput = outputPathForSource(source);
    const outputPath = path.resolve(ROOT, candidateOutput);
    const analysis = await analyzeLosslessWebp(sourcePath);
    if (analysis.savingsRatio < policy.minimumSavingsRatio) {
      throw new Error(
        `lossless WebP savings below ${policy.minimumSavingsRatio}: ${source} (${analysis.savingsRatio})`
      );
    }
    const materialized = image.admission.status !== 'rejected';
    if (materialized) {
      materializeLosslessWebp(outputPath, analysis.encoded, checkOnly);
    } else if (fs.existsSync(outputPath)) {
      if (checkOnly) {
        throw new Error(`rejected optimized UI image output must not ship: ${candidateOutput}`);
      }
      fs.unlinkSync(outputPath);
    }
    if (image.admission.status === 'admitted') admittedMapping[source] = candidateOutput;
    images.push({
      source,
      candidateOutput,
      output: materialized ? candidateOutput : null,
      criticalPath: image.criticalPath === true,
      admission: image.admission,
      measurement: image.measurement,
      width: analysis.width,
      height: analysis.height,
      hasAlpha: analysis.hasAlpha,
      sourceBytes: analysis.sourceBytes,
      outputBytes: analysis.outputBytes,
      savedBytes: analysis.savedBytes,
      savingsRatio: analysis.savingsRatio,
      sourceSha256: analysis.sourceSha256,
      outputSha256: analysis.outputSha256,
      visiblePixelsEqual: analysis.visiblePixelsEqual
    });
  }

  const manifest = {
    schemaVersion: 1,
    codec: 'webp-lossless',
    minimumSavingsRatio: policy.minimumSavingsRatio,
    policy: browserPath(POLICY_PATH),
    images,
    admittedMapping
  };
  const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
  const moduleText = renderGeneratedModule(admittedMapping);
  assertGeneratedText(
    MANIFEST_PATH,
    manifestText,
    checkOnly,
    'optimized-ui-images.json is stale; run npm run assets:ui-images:build'
  );
  assertGeneratedText(
    GENERATED_MODULE_PATH,
    moduleText,
    checkOnly,
    'optimized-ui-images.generated.ts is stale; run npm run assets:ui-images:build'
  );
  console.log(
    `[optimized-ui-images] verified=${images.length} admitted=${Object.keys(admittedMapping).length}`
  );
}

void run().catch((error) => {
  console.error(error instanceof Error ? error.stack || error.message : error);
  process.exitCode = 1;
});
