interface MatchWorkerRuntimeGlobalScope {
    SharedConstants?: unknown;
    SharedBoardUtils?: unknown;
    DeckSpecHelpers?: unknown;
    DeckCodecModule?: unknown;
    PlayerEncoding?: unknown;
    DestroyOutcomeContract?: unknown;
    StoneStatusSnapshot?: unknown;
    SpecialStoneRegistry?: unknown;
    PresentationEffectProfiles?: unknown;
    CardRandomSource?: unknown;
    CardStateFactory?: unknown;
    CardModuleResolver?: unknown;
    CardPresentationHelpers?: unknown;
    CardHandManager?: unknown;
    CardChargeLedger?: unknown;
    CardPendingStateManager?: unknown;
    CardUsagePrechecks?: unknown;
    CardEffectTiming?: unknown;
    CardExpansion?: unknown;
    CardMovement?: unknown;
    CardTeleport?: unknown;
    CardClone?: unknown;
    CardMeteor?: unknown;
    CardShrink?: unknown;
    CardLivingWill?: unknown;
    CardTargets?: unknown;
    CardFlips?: unknown;
    CardChain?: unknown;
    CardRegen?: unknown;
    CardTimeBomb?: unknown;
    CardBreeding?: unknown;
    DragonEffects?: unknown;
    CardUdg?: unknown;
    CardHyperactive?: unknown;
    CardSniper?: unknown;
    CardLightning?: unknown;
    CardWillHunterKing?: unknown;
    CardDestroyDragon?: unknown;
    CardSelectors?: unknown;
    CardWork?: unknown;
    CardMarkers?: unknown;
    BoardOps?: unknown;
    DestroyOneStoneEffects?: unknown;
    SwapWithEnemyEffects?: unknown;
    CardProtectEffects?: unknown;
    CardTrapEffects?: unknown;
    CardOwnershipEffects?: unknown;
    CardBoardExpansionApply?: unknown;
    CardHandEffects?: unknown;
    CardPositionSwapEffects?: unknown;
    CardStatusCellsEffects?: unknown;
    CardStateManager?: unknown;
    CardEffectResolver?: unknown;
    CardTimingProcessor?: unknown;
    CardTargetResolver?: unknown;
    CardCatalog?: unknown;
}

function getRuntimeGlobalScope(): MatchWorkerRuntimeGlobalScope {
    if (typeof globalThis !== 'undefined') return globalThis as MatchWorkerRuntimeGlobalScope;
    if (typeof self !== 'undefined') return self as MatchWorkerRuntimeGlobalScope;
    return {};
}

function unwrapModule(mod: unknown): unknown {
    return mod && typeof mod === 'object' && 'default' in mod ? mod.default : mod;
}

const scope = getRuntimeGlobalScope();

if (!scope.CardCatalog) scope.CardCatalog = unwrapModule(require('../cards/catalog.js'));
if (!scope.SharedConstants) scope.SharedConstants = unwrapModule(require('../shared-constants.js'));
if (!scope.SharedBoardUtils) scope.SharedBoardUtils = unwrapModule(require('../shared/shared-board-utils.js'));
if (!scope.DeckSpecHelpers) scope.DeckSpecHelpers = unwrapModule(require('../shared/deck-spec.js'));
if (!scope.DeckCodecModule) scope.DeckCodecModule = unwrapModule(require('../shared/deck-codec.js'));
if (!scope.PlayerEncoding) scope.PlayerEncoding = unwrapModule(require('../shared/player-encoding.js'));
if (!scope.DestroyOutcomeContract) scope.DestroyOutcomeContract = unwrapModule(require('../shared/destroy-outcome-contract.js'));
if (!scope.StoneStatusSnapshot) scope.StoneStatusSnapshot = unwrapModule(require('../shared/stone-status-snapshot.js'));
if (!scope.SpecialStoneRegistry) scope.SpecialStoneRegistry = unwrapModule(require('../shared/special-stone-registry.js'));
if (!scope.PresentationEffectProfiles) scope.PresentationEffectProfiles = unwrapModule(require('../shared/presentation-effect-profiles.js'));
if (!scope.CardRandomSource) scope.CardRandomSource = unwrapModule(require('../game/logic/cards-internal/random-source.js'));
if (!scope.CardStateFactory) scope.CardStateFactory = unwrapModule(require('../game/logic/cards-internal/state-factory.js'));
if (!scope.CardModuleResolver) scope.CardModuleResolver = unwrapModule(require('../game/logic/cards-internal/module-resolver.js'));
if (!scope.CardPresentationHelpers) scope.CardPresentationHelpers = unwrapModule(require('../game/logic/cards-internal/presentation-helpers.js'));
if (!scope.CardHandManager) scope.CardHandManager = unwrapModule(require('../game/logic/cards-internal/hand-manager.js'));
if (!scope.CardChargeLedger) scope.CardChargeLedger = unwrapModule(require('../game/logic/cards-internal/charge-ledger.js'));
if (!scope.CardPendingStateManager) scope.CardPendingStateManager = unwrapModule(require('../game/logic/cards-internal/pending-state-manager.js'));
if (!scope.CardUsagePrechecks) scope.CardUsagePrechecks = unwrapModule(require('../game/logic/cards-internal/card-usage-prechecks.js'));
if (!scope.CardEffectTiming) scope.CardEffectTiming = unwrapModule(require('../game/logic/cards-internal/effect-timing.js'));
if (!scope.CardExpansion) scope.CardExpansion = unwrapModule(require('../game/logic/cards/expansion.js'));
if (!scope.CardMovement) scope.CardMovement = unwrapModule(require('../game/logic/cards/movement.js'));
if (!scope.CardTeleport) scope.CardTeleport = unwrapModule(require('../game/logic/cards/teleport.js'));
if (!scope.CardClone) scope.CardClone = unwrapModule(require('../game/logic/cards/clone.js'));
if (!scope.CardMeteor) scope.CardMeteor = unwrapModule(require('../game/logic/cards/meteor.js'));
if (!scope.CardShrink) scope.CardShrink = unwrapModule(require('../game/logic/cards/shrink.js'));
if (!scope.CardLivingWill) scope.CardLivingWill = unwrapModule(require('../game/logic/cards/living_will.js'));
if (!scope.CardTargets) scope.CardTargets = unwrapModule(require('../game/logic/cards/targets.js'));
if (!scope.CardFlips) scope.CardFlips = unwrapModule(require('../game/logic/cards/flips.js'));
if (!scope.CardChain) scope.CardChain = unwrapModule(require('../game/logic/cards/chain.js'));
if (!scope.CardRegen) scope.CardRegen = unwrapModule(require('../game/logic/cards/regen.js'));
if (!scope.CardTimeBomb) scope.CardTimeBomb = unwrapModule(require('../game/logic/cards/time_bomb.js'));
if (!scope.CardBreeding) scope.CardBreeding = unwrapModule(require('../game/logic/cards/breeding.js'));
if (!scope.DragonEffects) scope.DragonEffects = unwrapModule(require('../game/logic/effects/dragon.js'));
if (!scope.CardUdg) scope.CardUdg = unwrapModule(require('../game/logic/cards/udg.js'));
if (!scope.CardHyperactive) scope.CardHyperactive = unwrapModule(require('../game/logic/cards/hyperactive.js'));
if (!scope.CardSniper) scope.CardSniper = unwrapModule(require('../game/logic/cards/sniper.js'));
if (!scope.CardLightning) scope.CardLightning = unwrapModule(require('../game/logic/cards/lightning.js'));
if (!scope.CardWillHunterKing) scope.CardWillHunterKing = unwrapModule(require('../game/logic/cards/will_hunter_king.js'));
if (!scope.CardDestroyDragon) scope.CardDestroyDragon = unwrapModule(require('../game/logic/cards/destroy_dragon.js'));
if (!scope.CardSelectors) scope.CardSelectors = unwrapModule(require('../game/logic/cards/selectors.js'));
if (!scope.CardWork) scope.CardWork = unwrapModule(require('../game/logic/cards/work_will.js'));
if (!scope.CardMarkers) scope.CardMarkers = unwrapModule(require('../game/logic/cards/markers.js'));
if (!scope.BoardOps) scope.BoardOps = unwrapModule(require('../game/logic/board_ops.js'));
if (!scope.DestroyOneStoneEffects) scope.DestroyOneStoneEffects = unwrapModule(require('../game/logic/effects/destroy_one_stone.js'));
if (!scope.SwapWithEnemyEffects) scope.SwapWithEnemyEffects = unwrapModule(require('../game/logic/effects/swap_with_enemy.js'));
if (!scope.CardProtectEffects) scope.CardProtectEffects = unwrapModule(require('../game/cards/effects/protect.js'));
if (!scope.CardTrapEffects) scope.CardTrapEffects = unwrapModule(require('../game/cards/effects/trap.js'));
if (!scope.CardOwnershipEffects) scope.CardOwnershipEffects = unwrapModule(require('../game/cards/effects/ownership.js'));
if (!scope.CardBoardExpansionApply) scope.CardBoardExpansionApply = unwrapModule(require('../game/cards/effects/board-expansion-apply.js'));
if (!scope.CardHandEffects) scope.CardHandEffects = unwrapModule(require('../game/cards/effects/hand-effects.js'));
if (!scope.CardPositionSwapEffects) scope.CardPositionSwapEffects = unwrapModule(require('../game/cards/effects/position-swap.js'));
if (!scope.CardStatusCellsEffects) scope.CardStatusCellsEffects = unwrapModule(require('../game/cards/effects/status-cells.js'));
if (!scope.CardStateManager) scope.CardStateManager = unwrapModule(require('../game/cards/state-manager.js'));
if (!scope.CardEffectResolver) scope.CardEffectResolver = unwrapModule(require('../game/cards/effect-resolver.js'));
if (!scope.CardTimingProcessor) scope.CardTimingProcessor = unwrapModule(require('../game/cards/timing-processor.js'));
if (!scope.CardTargetResolver) scope.CardTargetResolver = unwrapModule(require('../game/cards/target-resolver.js'));

export {};
