// Generated by scripts/assets/build-optimized-ui-images.ts. Do not edit.
export const OPTIMIZED_UI_IMAGES = Object.freeze({} as const);

export type OptimizedUiImageSource = keyof typeof OPTIMIZED_UI_IMAGES;
