// Generated by scripts/assets/build-background-images.ts. Do not edit.
export const OPTIMIZED_BACKGROUND_IMAGES = Object.freeze({} as const);

export type OptimizedBackgroundSource = keyof typeof OPTIMIZED_BACKGROUND_IMAGES;
