// Generated by scripts/assets/build-optimized-ui-images.ts. Do not edit.
export const OPTIMIZED_UI_IMAGES = Object.freeze({
  "assets/images/board/board-frame-marsh-forged-iron-v1.png": "assets/images/board/board-frame-marsh-forged-iron-v1.webp",
  "assets/images/board/board-frame-submerged-wood-v1.png": "assets/images/board/board-frame-submerged-wood-v1.webp"
} as const);

export type OptimizedUiImageSource = keyof typeof OPTIMIZED_UI_IMAGES;
