// Generated by scripts/assets/build-optimized-ui-images.ts. Do not edit.
export const OPTIMIZED_UI_IMAGES = Object.freeze({
  "assets/images/board/board-surface-bluegreen-felt-v1.png": "assets/images/board/board-surface-bluegreen-felt-v1.webp",
  "assets/images/board/board-frame-submerged-wood-v1.png": "assets/images/board/board-frame-submerged-wood-v1.webp",
  "assets/images/background/デフォルト25.png": "assets/images/background/デフォルト25.webp",
  "assets/images/other/card-back-deck-v1.png": "assets/images/other/card-back-deck-v1.webp",
  "assets/images/other/card-back-hand-v1.png": "assets/images/other/card-back-hand-v1.webp",
  "assets/images/ui/card-area-table-player-v6.png": "assets/images/ui/card-area-table-player-v6.webp",
  "assets/images/ui/card-area-table-opponent-v6.png": "assets/images/ui/card-area-table-opponent-v6.webp",
  "assets/images/other/charge-counter-wafu-v1.png": "assets/images/other/charge-counter-wafu-v1.webp",
  "assets/images/other/charge-delta-increase-wafu-v1.png": "assets/images/other/charge-delta-increase-wafu-v1.webp",
  "assets/images/other/charge-delta-decrease-wafu-v1.png": "assets/images/other/charge-delta-decrease-wafu-v1.webp",
  "assets/images/other/turn-banner-your-v1.png": "assets/images/other/turn-banner-your-v1.webp",
  "assets/images/other/turn-banner-your-white-v1.png": "assets/images/other/turn-banner-your-white-v1.webp",
  "assets/images/other/turn-banner-enemy-v1.png": "assets/images/other/turn-banner-enemy-v1.webp",
  "assets/images/other/turn-banner-enemy-black-v1.png": "assets/images/other/turn-banner-enemy-black-v1.webp"
} as const);

export type OptimizedUiImageSource = keyof typeof OPTIMIZED_UI_IMAGES;
